### ISSUE TITLE
order timing restaurant

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-web#1098]
On sicko.coopcycle.org "La cantina d'anna" order timing are program but client see delivery between 0-5 min. 

<img width="960" alt="Client view" src="https://user-images.githubusercontent.com/59088580/73014766-0a88d480-3e1b-11ea-9705-a0bf54abdfb7.png">
<img width="960" alt="timing order" src="https://user-images.githubusercontent.com/59088580/73014768-0a88d480-3e1b-11ea-8cb9-bde8f9511704.png">

**Comment by alexsegura** [comment]
The `shippingOptionsDays` property of the restaurant was set to 0, thus the platform returned no results for shipping options. 

Fixed in 03c1874a81d4e6542b0b6364023b421d078fad55 by adding more validation on this propperty

<img width="609" alt="Capture d’écran 2020-01-24 à 10 12 36" src="https://user-images.githubusercontent.com/1162230/73057639-54f96800-3e92-11ea-9194-5200164e4607.png">
