### ISSUE TITLE
Time slots shown as the opening times.

### ISSUE THREAD

**Issue by Pidgeon45** [coopcycle/coopcycle-web#1353]
When time slots are selected as the 'behaviour of opening hours', these are displayed as the opening hours on the customer facing restaurant page, rather than the absolute opening hours.

**Comment by Pidgeon45** [comment]
Could opening times an delivery slots be made seperate fields?

**Comment by PasLoin** [comment]
I have the same issue ; i setup delivery for Wednesday AND Saturday and it's displayed : Wednesday to Saturday

**Comment by alexsegura** [comment]
@PasLoin can I see the exact setup of opening hours please? A screenshot would help

**Comment by PasLoin** [comment]
Ok i understand my mistake it was configured like this : 

![Sans titre](https://user-images.githubusercontent.com/25326871/80853565-224dd100-8c32-11ea-9b3d-293cc61e3e38.png)

And the correct configuration is this : 

![Sans titre2](https://user-images.githubusercontent.com/25326871/80853590-49a49e00-8c32-11ea-810f-e1e7a81f2c47.png)

**Comment by PasLoin** [comment]
First give that : 
![notok](https://user-images.githubusercontent.com/25326871/80853802-bb311c00-8c33-11ea-8e22-ab4fe810dfe9.png)
Second config give that : 
![ok](https://user-images.githubusercontent.com/25326871/80853820-cc7a2880-8c33-11ea-8f70-6bcb7bc2aebb.png)

A little confusing still exist : its delivery slot not opening hour.

**Comment by agichim** [comment]
It would be even better if the opening times of a restaurant that are visible to the customer are not called from the schedule/slots which we configure in Restaurant settings.
Instead, there could be **1 option** to configure opening times (what the customer sees), see image 
![image](https://user-images.githubusercontent.com/51931067/81540531-b3772300-9369-11ea-9abe-f5c5110ad4d5.png)

and the **other option** that we have now, the configuring of the schedule/slots stays only for backend use, so we can use as many time slots as we fancy, etc. Of course, it means we need to manually make sure that the 2 options reflect each other. 

What we did, was use 1 hour time slots for Thursday, Friday, Saturday and Sunday, and when we did that we had a very large list of opening times, like this ↓

![image](https://user-images.githubusercontent.com/51931067/81545877-77e05700-9371-11ea-8026-f4f4c1ad0e52.png)

**Comment by agichim** [comment]
As this issue says, there should be a separate setting for showing the opening times of a restaurant, respective of either Collection or Delivery.

Possibly look into the way Deliveroo do it. On the app they have 2 general tabs `Delivery` and `Collection`. When either tab is clicked the whole website refreshes showing the Businesses that do delivery or collection, if they do both, the businesses are shown in both Delivery and Collection.

Maybe in the same pop-up where the user is prompted to input the address make it mandatory to choose "Delivery" or "Collection. Inputting address can stay the same, not mandatory. 
Something like this? 
![image](https://user-images.githubusercontent.com/51931067/100923755-96599b80-34d7-11eb-8044-bfce38be8429.png)
Deliveroo make it mandatory to input the address before seeing the businesses. (I think this was discussed at some point).

If the customer changes their mind, and they want to Collect their food instead of having it Delivered, Deliveroo's way of doing seems pretty cool.

When on the specific business homepage you have this option:
![image](https://user-images.githubusercontent.com/51931067/100924960-3fed5c80-34d9-11eb-8434-6b99bbcf8c47.png)

When you click `Change` you get this popup
![image](https://user-images.githubusercontent.com/51931067/100925035-58f60d80-34d9-11eb-826b-eecaacd3697e.png)

If that business doesn't offer "Collection" than it should still show but it should be disabled, not clickleabe. In the same popup maybe they can also change their address and timeslot.
