### ISSUE TITLE
Allow renaming zones 

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-web#1385]
Low priority but can be usefull.

**Comment by alexsegura** [comment]
The problem is that zone names are used in pricing rules expressions (example: `in_zone(dropoff.address, "City_Center")`)
It was a bad idea to use names in the first place, it was done like this because it's easier to read. In any case, if we allow to rename zones, we would need first to rely on something immutable in pricing rule expressions (like, for example, the ID)
