### ISSUE TITLE
Avoid expired Stripe charges

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#1388]
If an order is placed more than 7 days in advance, the Stripe charge may has expired when the dropoff task is completed, leading to lost money.

The system should do a few things to avoid this:
- Add a scheduled script that checks charges that are going to expire
- Do not propose time slots that are incompatible with authorize/capture time limits

Another solution would be to capture the charge when the restaurant accepts the order.

**Comment by joel-shiftdelivery** [comment]
I think the first two ideas are good. 

I'm very hesitant about capturing when the restaurant accepts the order, instead of when the order is placed. The payment could be declined at that time, which could make a bad customer experience since they "already placed the order" and there wouldn't be an easy way to fix the payment at that point.

Having payment captured when the order is placed allows for the customer to immediately fix things or provide a different payment card if the first one is declined.

**Comment by alexsegura** [comment]
Fixed in 9927c4649be41d492034b7fe10da573ccbdc7ead
