### ISSUE TITLE
Upgrading the integration form

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1423]
Over time, some good functionalities have been added to the stores or restaurants (opening time, timeslot, additional time for taking orders, delivery zone,...). 

It will be helpfull to upgrade the integration form with the same functionnalities. With the covid19 crisis, some individuals contacts us by phone to order a delivery but these B2C deliveries aren't profitable without automatic ordering and paiement.

**Comment by rayon9coop** [comment]
Add a filed VAT number in the Facturation form

**Comment by alexsegura** [comment]
I totally agree. 

Actually, we need to introduce a "delivery form" concept in the platform. 
A "delivery form" is a (configurable) form that allows to create a delivery in the system. 

Then, instead of having options on the "store" page, we would just have one dropdown listing all the forms available. It could even be possible to re-use the same form for multiple "stores". 

The "embeddable" form would just be one form like another one. 
Maybe, to allow embedding it somewhere, each form would expose a "public url".

**Comment by alexsegura** [comment]
Also see #1700
