### ISSUE TITLE
Define amount of available items of a product [Restaurant]

### ISSUE THREAD

**Issue by 552020** [coopcycle/coopcycle-web#1580]
In order to improve the management of the "products" it would be nice to have the possibility for the restaurant-manager to set the amount of a certain items (dishes: hummus, pizza margherita, etc.) that are available for sell in the platform. The customer doesn't have to see it but when the defined number of items is sold then this product would be automatically turned off.

**Comment by alexsegura** [comment]
This means inventory management, and this can be complicated to manage, and lead to other problems, for example if the stock is wrong, for some reason. 

What is the real problem we are trying to fix here? 
Isn't the real problem, that when a product is out of stock, the only solution right now is to cancel the order?

Can't this be fixed with what is suggested in #1355, i.e allow the restaurant owner to edit the order (remove an item / reduce the quantity)?

**Comment by alexsegura** [comment]
Another potential problem pointed out by @joel-shiftdelivery

> it would also mean that people ordering in advance wouldn't be able to order their desired item, even if it will be back in stock by their selected delivery time

**Comment by agichim** [comment]
What Joel says is true. But everything has stock levels today. I guess that when you do pre-orders you probably don't do on-demand with that same store. And if stock levels get to zero they can easily be put up again so that person can pre-order their item for their desired delivery date. Because a store owner will know if they will have stock up again for that specific day, so the stock doesn't have to stay in zero, it can be update beforehand. Also, maybe people buy overnight and if you have stock levels you make sure you don't oversell overnight.

Regarding on-demand for stock levels it helps the restaurants to not have to worry about disabling products whilst their cooking, especially if it's busy.

**Comment by agichim** [comment]
I understand the thing with fresh food.

I'm adamant about stock levels because of feedback we got. 

The app giving a notification to stores/restos about updating stock is not a necessity, it's simply an extra feature which can be added later. 

>If stock is "more or less" easy to implement, this would be my ideal image:
>1. Admin or Shop/Resto owner can enable/disable the ability to use stock levels or not.
>- If "Stock" is enabled, there should be a box (placeholder) for each product where you can input a number.
>- If "Stock" is disabled there is no box to input a number in, it would look like it is currently.
>2. With "Stock" enabled, when the number reaches zero that product gets disabled automatically.
>3. The store/resto owners update the stock themselves. It doesn't have to reach zero either, they can update it when they want. 
>4. In the case of pre-orders, they can easily leave products in stock even if they don't have them because they know they will get more stock for the day the products need delivering to customers/recipients.

The owners of stores/restos they always kind of know their stock levels, so they will be aware when they have to update their stock levels, as the resto owner you spoke with, it would be easier for him to update stock on his own cashier and on the platform and not have to worry about anything. And "Stock" is also good value to offer to clients when we offer them to be on the platform.

I'm not saying Stock levels is something we need ASAP but I believe it is a priority.

**Comment by goodconcepts** [comment]
If you do, you need to offer an API as well to synchronize stock levels
with Point Of Sale to avoid discrepancies between online stock shown and
actual stock.

I would not prefer to have restaurants update stock by hand.
Op zo 18 okt. 2020 om 13:13 schreef agichim <notifications@github.com>

**Comment by agichim** [comment]
Yeah, makes sense. API will work only if shops keep stock on their own software. But the stock they would manually input on CoopCycle can always be less than the real stock they have or they can even have stock set aside which is being sold on CoopCycle.

**Comment by 552020** [comment]
> This means inventory management, and this can be complicated to manage, and lead to other problems, for example if the stock is wrong, for some reason.
> 
> What is the real problem we are trying to fix here?
> Isn't the real problem, that when a product is out of stock, the only solution right now is to cancel the order?
> 
> Can't this be fixed with what is suggested in #1355, i.e allow the restaurant owner to edit the order (remove an item / reduce the quantity)?

We had a request of a restaurant that feared to go out of products and didn't want to remain without certain products for in house customers. This was a critical issue for them. 

Another restaurant we have would like to have it but felt they considered it as less critical.

**Comment by ChloeOLVO** [comment]
@agichim what is the decision taken with this issue? Will it be implemented or it's too complicated and we leave it that way? (I'm asking because several restaurants on Paris asked for it :) )

**Comment by Paul-Eraman-CoopCycle** [comment]
closed as not planned right now
