### ISSUE TITLE
Can't save a Store

### ISSUE THREAD

**Issue by rsc93** [coopcycle/coopcycle-web#1649]
Le bouton enregistrer n'est plus fonctionnel.

**Comment by agichim** [comment]
I think you have to select a `tag` from the dropdown menu when creating a store. If you don't have any tags, create a tag first, give it the name of the store, perhaps, and then try creating the store again. It should work this way. 

And after you created a store and you change store settings and save them, make sure the tag is selected in the settings, otherwise you can't save the settings. And this applies for all the stores you already have created. Select a tag for all those stores so that you can save the settings.

**Comment by alexsegura** [comment]
Ok, it's a bug introduced in 7c004960bcf55c63b43f258b2a74a23b3446254d
