### ISSUE TITLE
In order to give a feedback to our customer I want coopcycle to automatically inform the customer once a task is done

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#1668]
**In order to**  inform our customer once a task is done
I would like coopcycle to send an information to the program of our customer (BioOffice) once a job is done. That would eliminate a lot of back and forth questions and improve the over all attractiveness of coopcycle and tricargo. 

**As** tricargo as a whole it would be more appealing to existing and new customers. Dispatcher and customer would benefit from it. 

**I want** that the information of a task being done is shown in BioOffice

**Whereas currently** there are a lot of back and forth questions.

**Comment by alexsegura** [comment]
Linked to #700

**Comment by ERAMANrepartos** [comment]
@GuidoHaagen Is this done? 
The only unclear part is what type of user - for example right nowthis happens with shop and restaurant orders, but not tasks imported to the admin panel, is that this case?

**Comment by GuidoHaagen** [comment]
@ERAMANrepartos 
yes. for us thats the case. But probably its best that we use orders if we need a notification.

**Comment by ERAMANrepartos** [comment]
Can i understand that the best solution to this problem is using orders rather than tasks, which creates the correct notifications? If so, I will close the issue.

this is because on a theoretical level, tasks are not associated with customer, orders are. tasks are anything we must do, sometimes simply this is a task to pass by a restaurant to talk with the owner. orders are a series of tasks that a client has asked that we do under a specific set of circumstances and want to know that these characteristics are fulfilled (a set of groups in a task do not have these characteristics for example). Anyways, please reply and I will close or not the issue accordingly

**Comment by ERAMANrepartos** [comment]
Sweet 🥳
