### ISSUE TITLE
More options for the "Packages" pricing condition

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1676]
In order to easely create complex tarification rules I want more options for the "Packages" pricing condition

**It would be helpfull to** 
Add some options that allows a custom number to be input:
- "ContainsLessThan"
- "ContainsMoreThan" 
- "ContainsExactly"
- "ContainsBetweenAnd"

**Whereas currently** `this happens`
For now, the only option for the "Packages" pricing condition, is "containsAtLeastOne".

**Comment by agichim** [comment]
I'd say Packages need a little re-thinking and re-factoring. 

Placing numbers in Volume units doesn't really do/mean anything.
![image](https://user-images.githubusercontent.com/51931067/121384708-6d133f80-c940-11eb-8e8d-71b13b2b093b.png)

Because a customer can choose a number of Packages here, but all it does is indicate how many packages of a specific size the customer has.
![image](https://user-images.githubusercontent.com/51931067/121384758-76041100-c940-11eb-932b-4a7af7cfd787.png)

**Comment by rayon9coop** [comment]
Not really since units volume is a criteria in the price settings

**Comment by ERAMANrepartos** [comment]
If i understand correctly, this is not useful now, so i am going to close the issue. however, i have added an epic "what are products" to the dev seminar 😃
