### ISSUE TITLE
Delivery times consisting of separated days show as range including days in-between

### ISSUE THREAD

**Issue by davidcryer** [coopcycle/coopcycle-web#1884]
**Describe the bug**
Delivery times consisting of separated days, e.g. Monday and Friday, show as "Monday to Friday" (including days in-between in language) rather than "Monday and Friday".

**To Reproduce**
1. Create new restaurant with deliveries time slots on Monday and Friday only
2. See delivery time description display as "Monday to Friday"

**Expected behavior**
Delivery time description should display as "Monday and Friday". If time slots differ between each day, then it would be nice if they are accurately described for each day, e.g. Monday 3pm - 5pm, Friday 1pm - 3pm

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by alexsegura** [comment]
You are right. 

The function that converts a [openingHours string](https://schema.org/openingHours) to a human readable string is in [this file](https://github.com/coopcycle/coopcycle-web/blob/f4c7d433e84861df0dfb106968384a2e99c3ca22/js/app/restaurant/parseOpeningHours.js)

The actual problem is that `TimeRange.parse` returns an array of days, no matter if it is a range or not

https://github.com/coopcycle/coopcycle-web/blob/f4c7d433e84861df0dfb106968384a2e99c3ca22/js/app/restaurant/parseOpeningHours.js#L11

This array is then passed to the translation library

https://github.com/coopcycle/coopcycle-web/blob/f4c7d433e84861df0dfb106968384a2e99c3ca22/js/app/restaurant/parseOpeningHours.js#L35-L40

And the translated string only works for ranges 

https://github.com/coopcycle/coopcycle-web/blob/f4c7d433e84861df0dfb106968384a2e99c3ca22/js/app/i18n/locales/en.json#L7

**Comment by alexsegura** [comment]
I suppose it could be fixed by changing `TimeRange.parse`, so that it returns an array, like:

```javascript
[
  { days, start, end },
  { days, start, end }
]
```

It would break the interface, but after a quick look it seems `TimeRange` is not used in a lot of code, so it should be easy. 

Would be cool at the same time to write Jest tests for the `parseOpeningHours` function.
