### ISSUE TITLE
Github project description inaccurately claims it is open source

### ISSUE THREAD

**Issue by afranke** [coopcycle/coopcycle-web#1908]
The projet description, visible in the About section at the right of [this page](https://github.com/coopcycle/coopcycle-web) but also as the organisation description on [this page](https://github.com/coopcycle) states:

> Open source logistics platform. Only for worker-owned business. 

This is a lie. The project is not open source. It is even explicitely stated on [the website](https://coopcycle.org/fr/logiciel/) or in [this comment](https://github.com/coopcycle/coopcycle-web/issues/494#issuecomment-435980543). These statements are correct because the commercial constraint of the license makes it incompatible with the open source definition (and the Free Software one).

**Comment by alexsegura** [comment]
Hi, 

While your message is a little bit rude and off topic, I will do my best to stay polite, and avoid ad-hominem attacks. 
Really, you should have contacted us by email instead of posting an issue. 
If you want to discuss further this "issue", we can definitely setup a video meeting. 

---

Actually, the term "open source" is not copyrighted, it does not belong to anybody. 
Its "inventor", Eric S. Raymond, tried to do so, but couldn't. If the OSI doesn't approve our license, it is not really a problem. 

We use the term "open source", because the source code is, well, actually, open. 
The source code can be read and modified by anyone. 

Actually, we identify more to the free software movement, but it's another debate. 

---

We "open sourced" (sorry) the platform, at the very beginning, for (at least) one good reason: this is a project that tries to offer a radical alternative to the gig economy platforms, platforms where workers are algorithmically governed by opaque algorithms, that decide, based on god knows what, about everything: who will get work, how much one will earn, and even who will get fired. 

So "algorithmic transparency" was one of the main reasons for "open sourcing" (sorry) the code. 
We thought that, if the code was readable by anyone, it would be a little bit easier for people that can read code to verify that the algorithm was "fair" (actually, this is not true anymore, because we don't have any algorithm to distribute work, the work is distributed manually by humans). 

---

But this project is not only about technology, it is in fact mainly a project about **work**. 
The gig economy platforms is basically a fancy trojan to change the structure of work (look at Prop22 in California). 
We don't want tech bros & free riders to use our software to make yet another gig economy platform to exploit workers. Instead, we want to enforce people to create businesses that do not seek only profit. 

We don't agree with the "no discrimination" stuff in the OSD. 
We think software should be used for good, not evil. 
Staying out of politics is actually a privilege. 

We are not harming FLOSS communities by doing what we do. 
There are already lots of issues with toxic behaviour in those communities. 

We were invited once to the Rencontres Mondiales du Logiciel Libre in 2018 in Strasbourg. 
And twice to the Journées du Logiciel Libre Lyon. 
And actually, the people there were not hostile at all with what we are doing, they were very welcoming 🙂 

Let's say we are heretics, but we are [not](https://notechforice.com/) [the](https://anticapitalist.software/) [only](https://wiki.p2pfoundation.net/Peer_Production_License) [ones](https://ethicalsource.dev/)

**Comment by bzg** [comment]
I think the OP has a point though.

You can play Alice's Adventures in Wonderland and use "open source" the way you want, but because the use of this term and its generally accepted meaning is strongly related to the use of OSI- or FSF-approved licenses, using it differently sounds like you are trying to mislead your users.

I have no doubt that you have very compelling reasons to use a nonfree license, but it would be clearer for everybody if you could use "ethical source" or some other term.

**Comment by Aspie96** [comment]
There is so much wrong on this thread replying is hard.
I hope @OpenSourceOrg comments too.

> Actually, the term "open source" is not copyrighted, it does not belong to anybody.
A term cannot be copyrighted. It can be tradmarked. Copyright and trademarks are two different things, WIDELY different things.

> Its "inventor", Eric S. Raymond, tried to do so, but couldn't. If the OSI doesn't approve our license, it is not really a problem.
Eric Raymond did NOT invent the term "open source". Christine Peterson did.

> Actually, we identify more to the free software movement, but it's another debate.
No, you do not.
If you did, the license would be a Free Software license. It is not.

> We don't agree with the "no discrimination" stuff in the OSD.
Good.
Then your project is not open source.

Open Source software absolutely only has one definition, which is approved by all OSI affiliates (including the Linux Foundation, Debian, the Wikimedia Foundation, the Wordpress Foundation, the Software Freedom Conservancy, The Mozilla Foundation, the GNOME Foundation, the Journal of Open Source Software, the FreeBSD Foundation, the LibreOffice Foundation, Drupal Association, Eclipse just to name a few), the Free Software Foundation (which does not like open source but recognizes its definition) and the Open Source community at large. The definition is also recognized by public institutions. Of course the definition is also supported by many other projects and initiative not mentioned.
There is no precedence of the term "open source" being used to refer to licenses prior to the Open Source Initiative, which is what popularized the term, with a very precise meaning (which comes from that of "free software").

You should read about the authority of the Open Source Initiative on the matter here:
https://opensource.org/authority
And why it matters: https://opensource.org/OSD_Affirmation

Sure, it is not a registered trademark (again, a name can't be copyrighted).
Nobody is claiming you are doing anything ILLEGAL by calling this software "open source".
It is not illegal. It is confusing, and inaccurate, which should be enough to fix it.

The correct term to use is "source available" (you did not open source anything, you merely published some source code), or any other term of your invention which you might like.

**Comment by Aspie96** [comment]
Also, linking to those other licenses as precedents is quite dishonest.

> Let's say we are heretics, but we are not the only ones

Really, let's look at them and see if they are "heretics" too.

- https://notechforice.com/

The phrase "open source" appears in two pages in the whole website. Never are proprietary licenses called "open source" by the website.

- https://anticapitalist.software/

This is an example of a website doing exactly that which you should do. They use a license which is not open source and they don't try to pretend it is. They explicitely say it is not.
> The Anti-Capitalist Software License is not an open source software license. It does not allow unrestricted use by any group in any field of endeavor, an allowance that further entrenches established powers. It also does not automatically release your project to the creative commons or public domain, nor does it require derived source code to be made available- although you may chose to release your work in this way.

I fully support anybody using any license they prefer, including non open source licenses. The issue is about what is being claimed. The Anti-Capitalist Software License is a perfect example of how this should be done and not a "heretic" at all. Do like them.

- https://wiki.p2pfoundation.net/Peer_Production_License

The phrase "open source" does not appear even once in the license. Again, nobody is wrongly misusing the sentence. "Open source" only appears in the discussion.

The only actual "heretic" in your list (somebody which is doing the same thing you are doing) is https://ethicalsource.dev/.
They have been called out multiple times for this (I think @OpenSourceOrg should comment more about them).
Their licenses are completely insignificant in the grand scheme of the software community as a whole. The only successful project released under one of their licenses is VCR (which got relicensed from MIT trough a huge fiasco, possibly violating the copyright of multiple contributors. Then it got fixed, but no apology was ever issue), which got successful way before adopting the license, when it actually was open source. VCR does not anywhere claim to be open source.

In essence, you linked to three examples of initiatives doing something which is entirely ok (using non-open source licenses without calling them "open source") and one initiative which, without any significant community behind it, started misusing the term "open source" without ever clarifying what they even mean by it at this point.

Since you linked to https://anticapitalist.software/, I ask you to fix this issue by doing exactly what they are doing and correcting the wording to avoid confusing your license with a open source license.
Nobody is saying you should not use the current license. Nobody is saying you are a "heretic" for using it. Nobody is saying it is a bad license.
Maybe it is the absolute best license in the world and it's good that you are using it, this issue is not about that.
It is simply about nomenclature: calling this project "open source" is a lie. It is not. Nobody said it should be.
