### ISSUE TITLE
In order to make it easier for the pricing choice As an admin I want to choose if I set my price with or without taxes in the pricing rules

### ISSUE THREAD

**Issue by MathildeS** [coopcycle/coopcycle-web#1919]
**In order to**  `make it easier for the pricing choice`
when I set the price for the delivery, the price is with taxes, while I do work without taxes when in B2B.
This may create some confusion and issues if I get it wrong!

**As a** `admin`
this will benefit admin work if we can choose to set the pricing rules with or without taxes

**I want** `choose if I set my price with or without taxes in the pricing rules`
In the pricing rules page, when I define the price, I want to choose if the price set is with or without taxes. 
- add a checkbox to say "I want to display the prices without taxes"
- and implement the logic behind :P 

**OR : clearly add in the UI that the prices set are with taxes !**

**Whereas currently** `this happens`
in the pricing rules page

**Comment by Paul-Eraman-CoopCycle** [comment]
This is something we talk about in the training sessions overall, but it is true it could be mentioned on the site on that page. I am going to make a new issue about adding that information on the page and close this issue, since making it modifiable would only introduce more complexity to the system
