### ISSUE TITLE
Add all address details in address book

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#2244]
- Phone number
- Contact name

**Comment by joel-shiftdelivery** [comment]
Also a "description" or "comment" field for things like a buzzer number or instructions like "access from rear alley" would be very helpful!

**Comment by rayon9coop** [comment]
Hi, is this something that is available ? If yes, how can we use it ?

**Comment by joel-shiftdelivery** [comment]
> Hi, is this something that is available ? If yes, how can we use it ?

@rayon9coop 
Yes, the address book is available for both individual users and Stores.

![Screenshot from 2021-05-03 03-39-22](https://user-images.githubusercontent.com/64277836/116867033-34ee4380-abc1-11eb-8fd3-b1a78fb841c0.png)
![Screenshot from 2021-05-03 03-35-25](https://user-images.githubusercontent.com/64277836/116867034-3586da00-abc1-11eb-84fa-03672f5f554d.png)

**Comment by rayon9coop** [comment]
Hi there,
I come back on this for different questions. I created several adresses in the address book but : 
- there's no possibility to edit or delete an existing address.
- there doesn't seem to be a link between the addresses existing in the address book and the tasks of deliveries. When I create a new delivery task, should it be possible to type in just the name and have all the details filled in automatically. Otherwise, I'm not sure what the point of the address book is ?
- As initially posted in this thread, it would be nice to have the phone number field added too.

Thanks in advance ! :)
