### ISSUE TITLE
Allow store users to download proofs of delivery

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#2300]

**Comment by ERAMANrepartos** [comment]
GOAL: To make a toggleable feature where store owners can see the photo or signature made in the app for each order delivered. 

![image](https://user-images.githubusercontent.com/77277854/115267357-61be4780-a139-11eb-8f89-4eec6eba182b.png)
1. To put a link to the signature/photo where i have a black box in this photo? And what would really make this kick-ass would be a search bar (blue) where you can search by date or address. Date better, because many are from and to the same place
