### ISSUE TITLE
!! Distance pricing does not calculate correctly

### ISSUE THREAD

**Issue by joel-shiftdelivery** [coopcycle/coopcycle-web#2463]
**Describe the bug**
When using distance pricing, the distance does not calculate in an understandable way. This affects both fixed distance prices and price by ranges

**To Reproduce**
1. Add items to basket from ShuckShuck at shift.coopcycle.org:
2. Enter 112 E Hastings as the address (<1km away) - See delivery fee is higher than it should be
3. Change address to 2500 Main St (~2km away) - See lower delivery fee
4. See error - After trying 5 addresses, not a single one calculated the correct price

**Expected behavior**
Distance fees should be calculated as they are set. In this instance, it should be $2 for each km over 1km

**Screenshots**
I tested with both price by ranges and fixed distance prices as shown

![Screenshot from 2021-05-28 13:41:54](https://user-images.githubusercontent.com/64277836/120039916-87513300-bfba-11eb-86a1-d6162bf36711.png)

![Screenshot from 2021-05-28 13:43:04](https://user-images.githubusercontent.com/64277836/120039971-a4860180-bfba-11eb-9a67-b2afd577c277.png)

**Device**
Affects both app and web ordering

**Additional context**
This is a critical bug.
Likely related to #2307

**Comment by alexsegura** [comment]
The actual problem is that the address stored for the restaurant has the wrong lat/lng. 

The lat/lng stored was [49.2684773,-123.1016717](https://www.openstreetmap.org/?mlat=49.26848&mlon=-123.10167#map=18/49.26848/-123.10167), but it's actually [49.28114670407457,-123.09885491534139](https://www.openstreetmap.org/?mlat=49.2811&mlon=-123.0989#map=15/49.2811/-123.0989)

I have changed it in database. 
Now it does this : 

With 112 E Hastings (distance calculated by OSRM = 336 meters)

```
Matched rule "order.itemsTotal < 2500"
```

With 2500 Main St (distance calculated by OSRM = 2160.7 meters)

```
Matched rule "order.itemsTotal < 2500"
Matched rule "distance in 2000..3000"
```

@joel-shiftdelivery can you try again, and confirm it as the problem? If yes, this issue an be closed, and the actual issue is the general issue about wrong address suggestions. Maybe the restaurant was created with another provider, like Algolia?

**Comment by alexsegura** [comment]
I'm pretty sure it was stored with Algolia. 
Geocode.Earth does not return any result for "227 E Pender Street" (😢), only one for "228 E Pender Street"

**Comment by alexsegura** [comment]
@joel-shiftdelivery the address coordinates has been changed to `49.28047, -123.09875`
