### ISSUE TITLE
 Use restaurant commercial address instead of company's head office address in tasks

### ISSUE THREAD

**Issue by biologeek** [coopcycle/coopcycle-web#2579]
**Describe the bug**

**To Reproduce**
1. Create a restaurant called Bagel Zée with a commercial address and a head office address
2. Put an order and validate it
3. In courier app, pickup task shows the address of the head office instead of restaurant address

**Expected behavior**
Bagel Zée has 2 different addresses for the official head office and the restaurant. When we received orders, we noticed that in courier app as well as on the website, tasks are to pick up at home office address while it should be at commercial address.

**Screenshots**
![Screenshot_20210629152032](https://user-images.githubusercontent.com/11749973/123804840-d823b680-d8ed-11eb-9cba-3b244402205d.png)

--

![Screenshot from 2021-06-29 15-22-59](https://user-images.githubusercontent.com/11749973/123804913-ed98e080-d8ed-11eb-9775-23ccceceb86f.png)

--

![Screenshot from 2021-06-29 15-23-36](https://user-images.githubusercontent.com/11749973/123805266-38b2f380-d8ee-11eb-8b4c-321b3b8b267b.png)

**Desktop (please complete the following information):**
 - OS: *
 - Browser *

**Smartphone (please complete the following information):**
 - Device: 
 - OS: Android 9
 - Browser *

**Additional context**
Linked to issue [#1133](https://github.com/coopcycle/coopcycle-app/issues/1133) in coopcycle-app

**Comment by alexsegura** [comment]
This is expected behaviour. The business address is only [used in receipts](https://github.com/coopcycle/coopcycle-web/blob/ac46e5593df03fbcc66479689c1fb2e4ac70e5a0/templates/order/receipt.pdf.twig#L35). This can't be inverted, as it would cause too much problems. 

It's just the label that is confusing, and with some help text it could be made crystal clear which one is used for what. 

In ac46e5593df03fbcc66479689c1fb2e4ac70e5a0 I added a help text that makes it more clear that the business address is used in receipts. We can also add help text on the "standard" address.
