### ISSUE TITLE
TaskEvent : Add more context to events

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#261]
For example "ASSIGN" event could be linked to courier id, so we can display a meaningful timeline to the user.
```
select * from task_event where task_id = 1532;
  id  | task_id |   name   |     created_at      | notes
------+---------+----------+---------------------+-------
 3505 |    1532 | DONE     | 2018-03-07 09:11:10 |
 3499 |    1532 | ASSIGN   | 2018-03-06 23:08:32 |
 3498 |    1532 | UNASSIGN | 2018-03-06 23:08:23 |
 3497 |    1532 | ASSIGN   | 2018-03-06 23:07:30 |
 3496 |    1532 | ASSIGN   | 2018-03-06 23:04:46 |
 3495 |    1532 | CREATE   | 2018-03-06 23:04:27 |
```

**Comment by PasLoin** [comment]
coursier and admin id is the minimal :)

**Comment by alexsegura** [comment]
The most flexible solution would be to add a `metadata` JSON column to store arbitrary data.

**Comment by Atala** [comment]
Maybe we could create an `AdminAction` entity (with courier, admin, aso) and the `TaskEvent` will link to it? 

In the future an `AdminAction` could then link to several `Events` - for ex. : 
Action "Cancel Task" links to : Unassign Task, Refund Task to customer, aso

Ref #173

**Comment by alexsegura** [comment]
Actually #173 & #261 are very similar. 

In `TaskEvent` we kind of already have the user information (because a `Task` is assigned to a user, we only lose it when it is unassigned, but this is kind of an edge case). 

I think it is more useful to start by #173, as it adresses the same problems in a more general way;
I have started a branch, it looks like this:

<img width="738" alt="capture d ecran 2018-03-24 a 00 30 04" src="https://user-images.githubusercontent.com/1162230/37857380-d5ed0790-2efa-11e8-849a-c65e6d830b5b.png">

**Comment by alexsegura** [comment]
Since 9659ec97af8d92eb4b640ae302fa675fdbacce73, task events store more data.
 
When a task is assigned, it records the username of the courier that has been assigned.
When a task is unassigned, it records the username of the courier previously assigned.

The `metadata` column contains the IP of the user performing the action, I'm also going to add the username of the person. 

```
 task_id |      name       |     created_at      |         data         |          metadata
---------+-----------------+---------------------+----------------------+---------------------------
      62 | task:unassigned | 2018-08-26 18:49:02 | {"username":"bot_1"} | {"client_ip":"172.19.0.1"}
      63 | task:unassigned | 2018-08-26 18:49:00 | {"username":"bot_1"} | {"client_ip":"172.19.0.1"}
      54 | task:unassigned | 2018-08-26 18:48:56 | {"username":"bot_1"} | {"client_ip":"172.19.0.1"}
      55 | task:unassigned | 2018-08-26 18:48:54 | {"username":"bot_1"} | {"client_ip":"172.19.0.1"}
      59 | task:assigned   | 2018-08-26 18:46:30 | {"username":"bot_1"} | {"client_ip":"172.19.0.1"}
      58 | task:assigned   | 2018-08-26 18:46:29 | {"username":"bot_1"} | {"client_ip":"172.19.0.1"}
```

**Comment by Atala** [comment]
Be aware that the `client_ip` may not be RGPD-compliant - what it's use for?

Very nice dev nevertheless, thanks :)
