### ISSUE TITLE
If it was possible to be able to tag customer accounts. Such customer is a regular customer, such customer has had a delivery problem ...

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-web#2686]
If it was possible to be able to tag customer accounts. Such customer is a regular customer, such customer has had a delivery problem ...

**Comment by ERAMANrepartos** [comment]
If done in a limited manner, this could be implemented relatively quickly. In a user´s configuration there could be for example:
VIP
Problematic
HadIncidents

These are the three most common things you may want to know. Then, there is the larger rework of how the customer database works. 

If this were created it would need to visualized in the following way:
restaurant: in the comments of the order, or a colored tag on the order before it is opened (in the orders page, visible without clicking on the order itself)
dispatch: as a colored tag on the order before it is opened in the orders page, and as a tag in the admin panel on the pickup and delivery tasks
rider: In the pickup and delivery tasks, and on the map with a colored point instead of a gray point

**Comment by Paul-Eraman-CoopCycle** [comment]
we did this!
