### ISSUE TITLE
Enable an admin to create a "sub stripe account" for a restaurant from its document

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#273]

**Comment by alexsegura** [comment]
Partially fixed in 6648f8829c401be7ac3a3dd11df72d18f7663ee8 & 5b3f40cdc868e89f59343c7174663a6b9b40b8a8

Actually, I just improved the previous implementation by retrieving more details from the Stripe Standard Account upon connection (`display_name` & `transfers_enabled`)

Also, it is now possible to specify the Stripe Account in the Restaurant / Store form. 

Now we still need to split funds.
