### ISSUE TITLE
User is able to register with a long username

### ISSUE THREAD

**Issue by biologeek** [coopcycle/coopcycle-web#2814]
**Describe the bug**
When registering, a user may input a long username with more than 15 characters. The form remains valid

**To Reproduce**
1. Go to Connection page then register as a new user
2. Input an invalid username with more than 15 characters
3. Fill the form with mandatory information
4. Click register then login to your account
5. Try to edit and save your profile. You should see an error with your username

**Expected behavior**
Register form should be considered invalid when username is longer than 15 characters

**Screenshots**

**Desktop (please complete the following information):**
 - OS: all
 - Browser all

**Additional context**

**Comment by alexsegura** [comment]
Can't reproduce, see GIF below. 

However, when you input an invalid username, the form group goes green, because this part of the code just checks if the username already exists or not, it doesn't care about the validity. 

![register_bug](https://user-images.githubusercontent.com/1162230/140280048-a7354541-55e1-419f-bd36-82a694f7b147.gif)

**Comment by alexsegura** [comment]
I noticed another problem, related to editing the username. 

Actually, when you edit the username, even if it's invalid:
1/ The invalid username is shown in the navbar.
2/ You are logged out.  

I think it's because it's bad practice to edit the user object directly, it is used by Symfony to do session/cookie checks.

https://github.com/coopcycle/coopcycle-web/blob/f22641f4a75d87923c417f4d53fc40e5fd31bed5/src/Controller/ProfileController.php#L127-L147

![edit_bug](https://user-images.githubusercontent.com/1162230/140284032-30394df0-82ba-451d-86cd-95ef96c018cf.gif)

**Comment by ERAMANrepartos** [comment]
Is this fixed? The second part I mean @alexsegura

**Comment by Paul-Eraman-CoopCycle** [comment]
@alexsegura ?

**Comment by alexsegura** [comment]
I just fixed the bug originally reported.
