### ISSUE TITLE
Cannot delete restaurants

### ISSUE THREAD

**Issue by ERAMANrepartos** [coopcycle/coopcycle-web#2959]
When trying to delete an old restaurant I get a 500 server error, and the restaurant does not get deleted.

1. Enter restaurant
2. Click red delete button
3. Wait for error
4. See restaurant still exists

**Expected behavior**
It deletes the restaurant

**Screenshots**

https://user-images.githubusercontent.com/77277854/145677976-80a67795-bee4-4720-98e0-13484585f4df.MOV

**Desktop (please complete the following information):**
Firefox and vivaldi

**Comment by alexsegura** [comment]
The problem is that even if restaurants are "soft deleted" (not really deleted, but flagged as deleted), the system still tries to propagate the removal to the linked objects (for example, orders), and it fails because of database constrains. 

<img width="1054" alt="Capture d’écran 2022-02-02 à 16 33 45" src="https://user-images.githubusercontent.com/1162230/152185505-e7a991d8-5fff-4e8d-84c0-401d150173a9.png">

It's a complicated problem, see related issue doctrine-extensions/DoctrineExtensions#1427

**Comment by alexsegura** [comment]
Actually, it was not the problem pointed above.
