### ISSUE TITLE
Repurposing old restaurants creates naming error

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#2974]
**Describe the bug**
When taking an unused restaurant profile and using it for a new restaurant (changing all the information in the profile including its name), on the admin Dashboard the order shows up with the original restaurant name along with the new one. The old incorrect name is in bold, and the new correct one in normal text

**To Reproduce**
1. create restaurant with its own info
2. wait an unknown amount of time
3. replace name with new name
4. make order
5. see error on admin dashboard panel 

**Expected behavior**
The correct name shows up

**Screenshots**
![image](https://user-images.githubusercontent.com/77277854/146673171-0a42b2f8-2074-4b50-9e5e-afb68bcc5c25.png)
![image](https://user-images.githubusercontent.com/77277854/146673190-7c14a986-20f8-43fc-9fa7-72bfc4524199.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AdrienSICKLO** [comment]
Same thing happens with stores?

**Comment by alexsegura** [comment]
It's because what's in bold in the "organization name" (which is attached to the task), and what's in normal text is the "address name" (an alias for the address). 

When a restaurant is updated, the address name is updated, but the organization name is not. 
The problem I see, if we update the organization name, is that all previous tasks will be updated.

**Comment by lucasferraro** [comment]
How about adding the possibility to Clone/Duplicate a restaurant?
With this action you can reuse all the information of an existing restaurant and assign to the new one new properties such as: name, logo, address, etc.
And you can keep the old restaurant (and the previous tasks will still refer to it) or you can delete it if it's no longer needed.

**Comment by ERAMANrepartos** [comment]
So that was a separate issue request I was going to make whenever I got around to it. Multiple times it would have been very useful to be able to 
1. copy and paste a restaurant to avoid redoing all the configurations (effectively could have a "template" unconnected restaurant)
2. Export menu products, options, etc. Recently would have saved a considerable amount of work for a coop that is opening with a restaurant that we are with, and it was also going to be helpful at some other point but I forget when it was...sorry
3

**Comment by alexsegura** [comment]
Also see #4500

**Comment by Paul-Eraman-CoopCycle** [comment]
Tacking in #4500
