### ISSUE TITLE
[Rayon9] Lang dropdown issue

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#302]
Not reproductible in dev but the dropdown is buggy on rayon9.coopcycle.org instance.

**Comment by alexsegura** [comment]
This is due to missing rows in the `sylius_locale` table in database: 

```
INSERT INTO sylius_locale (code, created_at, updated_at) VALUES ('fr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sylius_locale (code, created_at, updated_at) VALUES ('en', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sylius_locale (code, created_at, updated_at) VALUES ('es', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
```

This was managed in a [migration](https://github.com/coopcycle/coopcycle-web/blob/4fc7dcb86cbeecca6fe97d47affb11995f9e302b/app/DoctrineMigrations/Version20180327140902.php), but migrations are not executed on new instances. 

We need to add this to the provisioning
