### ISSUE TITLE
Improve UX for exports: one single export with all relevant information

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3045]
- [ ] @Titooo94 Provide an example spreadsheet of what is expected

Right now, there are 2 places in which you can export information from the platform:

## Export of tasks from the dashboard

- Task number
- Type
- Address Name
- Address
- GPS Coordinates
- Address description
- After
- Before
- Status 
- Comments 
- Eventdone notes 
- Eventfailed notes 
- Finished at 
- Courier 
- Tag 
- Address contact name 
- Organisation

## Export of deliveries

- Organisation 
- Pick up address 
- Pick up after 
- Drop Off Address 
- Drop off before 
- Weight 
- Distance 
- Order Number 
- Order total 
- Packages

It looks like it is also missing an alias to identify deliveries. 

Having all important information in one single export would be very helpful

**Comment by alexsegura** [comment]
Generally speaking, it would be smart to move this extract to `Cube`. This way, we can benefit from `Cube`'s caching capabilities, and also it's almost already available via the API.

**Comment by ERAMANrepartos** [comment]
![image](https://user-images.githubusercontent.com/77277854/225894407-46ee0388-6d8b-46a7-886e-48eeca972d32.png)
Here we can see two issues that should be resolved in this improvement

1. that order codes that use the letter E are understood in excel as a representation of thousands, which makes data cleaning, ordering, and cleaning impossible
2. the date / time format is inoperable 

Possible solutions:
1.A: do something about excel formats that I don´t know how to do so that it understands all orders as text
1.A: Disallow the letter E from order codes
2.A: have a date column with standarized format and no time (DD/MM/YYYY) (if it is this way, than its not month "6" its month "06" and another column with hour done the same way (HH:MM:SS or HH:MM)
2.B: something else about excel formats that I don´t know how to do

**Comment by ERAMANrepartos** [comment]
Hey, so I have reviewed the deployed feature. There are a few issues. 
1. We have at minimum, every pickup and dropoff duplicated, and sometimes in triplicate 


![Image](https://user-images.githubusercontent.com/77277854/232333746-0663a1e4-2c90-4e09-9af3-c33ed90076e7.png)


2. It appears there are no comments being registered, since I know that riders have been making comments for all the pickup orders


![Image](https://user-images.githubusercontent.com/77277854/232333773-74ef7ffb-d2d7-49b4-b272-9b057ab0847b.png)


3. At the end there are a number of tasks with no "ordernumber" or order ID code (not sure about vocabulary, its the 2nd and 3rd columns) and strangely, in this orders there are two comments.


![Image](https://user-images.githubusercontent.com/77277854/232333781-3980339c-f65c-4e7f-a1fd-13337b3846c4.png)



photos attached. I will move the issue out of "done" in projects given these issues

Lastly, there was some confusion on the subject but I thought it was addressed. It is vital that we have the dynamic price for a store delivery, and the price for the cooperative for food delivery orders as well. 
Specifically, it should include the following:
Stores: Total price charged to the store; names of pricing rules or products that have created this price
Restaurants: Total cart amount, total paid, total for coopcycle cooperative (all with IVAs)

otherwise, this cannot be used for economic control as we talked about. That said, maybe we can turn this into 2 issues, 1 about implementing all relevant nonprice information, and another issue about adding all relevant pricing issue, given that the pricing is related to the separate issue about multi-dropoff and multi-pickup orders and dynamic pricing

**Comment by ERAMANrepartos** [comment]
Sorry, I need to edit point 2

It does have the correct comments in event.DONE.notes, but i couldn't see them because the "comments" column had been made 25 cm wide due to a formatting issue and I thought the excel was empty from there to the right. Once I resized the column, all good. Can we change the way the export is formatted so that this doesn't happen somehow? 


![Image](https://user-images.githubusercontent.com/77277854/232334084-d40a8a29-de91-484b-8a96-0a1baa86aec0.png)

**Comment by lucasferraro** [comment]
Working on reported bugs

**Comment by ERAMANrepartos** [comment]
Still getting repeating tasks ☹ 


![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/93ca6081-290d-4a12-90a7-28403404969a)

**Comment by alexsegura** [comment]
For an unknown reason, a missing `Content-Type` header was causing empty files, only in production

Should be fixed in df74398e21659e288ff717638dcd1bde5b23a2c9

**Comment by alexsegura** [comment]
Actually, the problem persists in production. Cube server only returns results on the 2nd HTTP call 🤔

**Comment by alexsegura** [comment]
In production, sometimes the Cube server responds with this: 

```
< HTTP/1.1 200 OK

<
* Connection #0 to host cubejs.coopcycle.org left intact
{"error":"Continue wait","stage":{"stage":"Executing query","timeElapsed":4985}}
```

**Comment by lucasferraro** [comment]
[Here](https://cube.dev/docs/http-api/rest/#prerequisites-continue-wait) says that we can adjust a config called [continueWaitTimeout](https://cube.dev/docs/config#queue-options) in order to change the time Cube waits before returning `Continue wait` message.

Also, could be helpful check logs and see how long it took for Postgres to execute the query. Seems like we could significantly speed the query up by adding a pre-aggregation layer in Cube. More info [here](https://morioh.com/p/5e35dfa720d4)

**Comment by alexsegura** [comment]
@lucasferraro yep, pre-aggregation should definitely be setup. For the moment, I'm just implementing a retry mechanism to hotfix the issue.

**Comment by alexsegura** [comment]
Retry strategy implemented in a66fdb31c38cf1f92a66bb2ca37c9bf52c72b58f

**Comment by Paul-Eraman-CoopCycle** [comment]
Test version currently has a column that has income for the coop IVA incluido if a store task (flowers) and total cart value if a platform shop order

We need a column that shows the cooperatives final income for each delivery. So price of the store task if a store task, OR the commission of a platform order minus stripe fees if a platform shop order

Remember, the point here is to have one column with the real life actually income of the cooperative for calculating income vs costs

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
