### ISSUE TITLE
Editing issues when recurrent task edit

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3306]
When editing recurrent rules, the addresses don't change. See GIF

![Recurrent problem when editing](https://user-images.githubusercontent.com/59842043/177354245-0344f36c-76d6-4e3b-88bd-e1eff0c3a324.gif)

**Comment by alexsegura** [comment]
It seems to be because what is stored in the `task_rrule.template` column in database is wrong. It contains at the same time an `@id` column, and properties. 

Example: 

```json
{
  "@type":"hydra:Collection",
  "hydra:member":[
    {
      "@type":"Task",
      "type":"PICKUP",
      "address":{
        "@id":"\/api\/addresses\/12487",
        "streetAddress":"20 Rue du Clos Feuqui\u00e8res, Paris, France",
        "postalCode":"75015",
        "contactName":"Jean Michel",
        "telephone":"+33606060606"
      },
      "after":"00:00",
      "before":"23:59",
      "comments":"Attention!!!!!!!"
    },
    {
      "@type":"Task",
      "type":"DROPOFF",
      "address":{
        "@id":"\/api\/addresses\/12488",
        "streetAddress":"30 Rue Pirandello, Paris, France",
        "postalCode":"75013",
        "contactName":"Marie Michelle",
        "telephone":"+33606060606"
      },
      "after":"00:00",
      "before":"23:59",
      "comments":"Pourquoi?"
    }
  ]
}
```

So probably the code in `TaskNormalizer::denormalize`

https://github.com/coopcycle/coopcycle-web/blob/4a60bbfa8ea4f5cc9c65aa069e3d168bbea07b09/src/Serializer/TaskNormalizer.php#L115

**Comment by biologeek** [comment]
Hi guys, another thing maybe related to that : 

When you change the address of a task created through a recurrent task, it modifies all other recurrent tasks created before and after. 

Indeed, it changes the address linked to all tasks but not the address of the recurrent entity :
![Screenshot from 2022-07-19 17-55-55](https://user-images.githubusercontent.com/11749973/179795637-d3c96565-8d38-49d6-a8ba-c514f526a6b8.png)


Created task : 

![Screenshot from 2022-07-19 17-56-26](https://user-images.githubusercontent.com/11749973/179795762-13f2a7d1-3803-446a-b79c-f3937be43610.png)

Task created before modification : 

![Screenshot from 2022-07-19 17-57-04](https://user-images.githubusercontent.com/11749973/179796753-a242263c-c78a-47e3-814f-e4dcbe80e202.png)


Task created after modification : 

![Screenshot from 2022-07-19 18-00-15](https://user-images.githubusercontent.com/11749973/179796658-e02b8bf8-38ce-42d2-bf4b-8b6003887601.png)
.

**Comment by alexsegura** [comment]
There is some code in [TaskRecurrenceRuleSubscriber](https://github.com/coopcycle/coopcycle-web/blob/28be69c966988d4aa24d0cfa0889d7a260e0e259/src/Doctrine/EventSubscriber/TaskRecurrenceRuleSubscriber.php) that persists the adresses entered in the modal (this is why we end up with addresses with an `@id`). 

We do this, to avoid duplicating addresses each time tasks are created. 

There are 2 issues here: 

1/ Make sure that address is updated when editing a recurrent rule, using duplication. We need to keep the previous address untouched, and recreated a new address, to avoid losing the database links. 

2/ When editing a task's address, we are actually modifying the address object in database. All other tasks that are linked to this address would have their address modified as well. For most users, when they modify the address of a task, it's not obvious that they will modify all other tasks. So, when a task's address is modified, we need to **create a new address**, instead of updating the existing address.
