### ISSUE TITLE
The number of packages does not match in dashboard

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3382]
**Describe the bug**
The number of packages is different as if it's mentionned in the tasks or on the summary of deliveries (in the dashboard)

**To Reproduce**
1. Create an order and select a package
2. Click on 'deliveries'
3. See the summury of the new delivery (the number of packages)
4. Click on the # number
5. See the details of the tasks (the number of packages)

**Expected behavior**
The same number of packages no matter where you look

**Screenshots**
![Dash](https://user-images.githubusercontent.com/44605344/187660796-2e821602-91ed-4dff-aba8-8394e184f54c.png)

![dash1](https://user-images.githubusercontent.com/44605344/187660812-6275183c-f0f4-4e79-91c1-1d3bc305b0be.png)

![PU1](https://user-images.githubusercontent.com/44605344/187660865-ef4f8e57-1c7b-403d-a573-443b860c2f1d.png)
![DO1](https://user-images.githubusercontent.com/44605344/187660880-1c92703b-372a-40fb-924d-51273de32ced.png)
![dash2](https://user-images.githubusercontent.com/44605344/187660891-eebdf860-9d6d-449a-9c11-cc430c7b5eef.png)
![PU2](https://user-images.githubusercontent.com/44605344/187660902-0b74c094-99ee-481f-ac6b-71d221cfa436.png)
![DO2](https://user-images.githubusercontent.com/44605344/187660911-b3d80cea-4991-45f4-8da5-b0cf4905c956.png)

**Comment by ERAMANrepartos** [comment]
This is a critical error, have we looked at this @alexsegura ??

**Comment by alexsegura** [comment]
It's "normal". 

For delivery 6449, the **pickup** has actually 3 packages attached (even if it's not shown in the delivery form), and the **dropoff** has 1 package. I don't know why packages are attached to the pickup, because we only allow packages to be attached to dropoffs. I looked in the database, and the last package attached to a pickup is at **3rd December 2022**. 

So it's showing 4 packages in the pickup, because we have some logic that sums up the number of packages of all subsequent dropoffs, so that the messenger knows how much to load in the bike. 

So I believe it's an old bug that has been fixed since. 

https://github.com/coopcycle/coopcycle-web/blob/31d298bcf2bd20694213cbb2dd9a5853201ab22a/src/Serializer/TaskNormalizer.php#L97-L104
