### ISSUE TITLE
Improve courier gps tracking 

### ISSUE THREAD

**Issue by RSCMontreuil** [coopcycle/coopcycle-web#3514]
To allow a better service

As a customer relationship manager / business developer

I want to allow stores to see couriers coming to pickup deliveries

Whereas currently GPS tracking is available only for dropoff tasks

Tracking should be available for the store, starting when the assigned courier finishes his previous task (I don't except couriers to be rigorous with the "start" button, and we always have previous tasks because we create "tour beginning" tasks in addition to delivery tasks) and ending at task completion. This should apply for pickup tasks as well as dropoff tasks.

**Comment by ERAMANrepartos** [comment]
Many cooperatives do not wish to let businesses see this information, for a wide variety of issues about privacy both for riders and the cooperative. This would also be very difficult to implement considering how assignment of tasks works. Generally, this need is fulfilled by a dispatcher. I am going to close this issue due to high level of specificity with high implications for other cooperatives.

If you believe this is a key feature we should implement, feel free to reopen the issue, and maybe add the characteristic that the feature could be turned on and off depending on the cooperative.
