### ISSUE TITLE
Import menus from other platforms

### ISSUE THREAD

**Issue by ZanyMonk** [coopcycle/coopcycle-web#3555]
As a consumer on a Coopcycle instance I often get calls from my restaurants saying **their menu wasn't up to date on their Coopcycle page**, because they often only do it on the main proprietary platform they're used to work with. I don't bother much myself, but this is clearly because it becomes **hard for restaurants to update their menus on many platforms**, so they forget or just don't do it.

I'm sure Coopcycle can implement some kind of solution to this problem. For example, a **restaurant could choose to "Always synchronise menus with my `external platform` restaurant"**, which would imply some connection to this platform's API. Menus could get updated each day via a cron job, or on push of a button.

UberEat and Deliveroo both have an API that would suit these needs, and others might too. Although it is technically possible, I have no clue about the legal shenanigans that could eventually make this a hassle.

What do you think about all this ?

**Comment by ERAMANrepartos** [comment]
Hi! There are a lot of issues here...
1. legal issues, as you mention
2. As we have seen recently, becoming reliant on the APIs of 3rd parties can become expensive the minute they decide to be assholes (👋 goodbye twitter)
3. There is not a huge amount of work really necessary
4. A restaurant that does not think to tell a cooperative about a changed menu may reflect a local problem in the relationship 

The best solution to this problem is an easier interface for the changing of menus, and a better relationship between the cooperative and restaurants where they communicate these changes because they consider the service as an important part of their business. I am going to close the issue, but please make a new issue that suggests features that improve the user experience of updating menus, since this would be a useful way to improve the platform for all users without relying on APIs from our competition.

**Comment by ERAMANrepartos** [comment]
Please take a look at the new discussion! It takes on this subject along with a few others.
