### ISSUE TITLE
Even if Saturday is checked, the time slot selector does not offer Saturday deliveries if "limit to working days" is checked

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3572]
**Describe the bug**
All is in the title :-)
<img width="690" alt="image" src="https://user-images.githubusercontent.com/44605344/224230948-54cf3304-e526-41fe-a046-9ec7c0bedc4f.png">

**Comment by ERAMANrepartos** [comment]
this entire feature is flawed from a basic level @alexsegura because in no place is "working day" defined. First, we do not know if saturdays are considered working days, this depends on the cooperatives. Any foodtech cooperative works on saturdays and we would never automatically deactivate saturdays right? Secondly, in Spain valentines day is not a holiday, but it is considered as a not working day by this feature, which created a large number of issues last year unexpectedly. 

Unless we plan on having up to date labor calendars for each country we work in, I would desactive completely this feature since it is not stable.
@alexsegura please respond with a plan for fixing this issue, or deactivating the feature

**Comment by Paul-Eraman-CoopCycle** [comment]
closing because it is as the feature is defined, although a future revamp of this could change things (will be there for future design)
