### ISSUE TITLE
In order to understand the status of my deliveries, As a store client, I want the dashboard to be more usable

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3585]
**In order to**  `achieve something`
Understand better the status and information associated with current, future and past deliveries

**As a** `role`
Store owner

**I want** `something to be added or changed`
To have a better dashboard. This could include:
1. A search bar for past deliveries
2. Proof of delivery opens as a pop up, doesn't download a zip file
3. Proof of delivery downloads a jpg not a zip file
4. Can filter by date ranges

**Whereas currently** `this happens`
The dashboard is organized non-chronologically, cannot find orders unless going page by page into the past...

**Additional context**
USE CASE 1: I am a store that sells flowers, and have 2-5 deliveries with my local cooperative per week. I want to know that the flowers have been delivered without incident, and be alerted when they are delivered to have peace of mind. I am not very technologically literate, so the email notifications are nice for me. Occasionally I have looked at a photo of the delivery out of curiosity, but unless I get a complaint i don't usually open the dashboard unless it is to see if something has already been delivered.

USE CASE 2: I am a small accounting firm and our primary business involves the activity of delivery certified mail to clients for important documents. It is a 1 in a 100 case that I need to prove that something has been delivered, but if I do, it is VERY important. I deliver between 5 and 30 letters per week, and need lots of visibility on their status. I regularly check the proof of delivery to see that everything is going well, just to be sure. I also am an accounting firm, so I have high expectations about getting a details note of delivery and invoice at the end of the month, especially since I pass along the cost of the delivery to my clients. I regularly look at past deliveries through the dashboard, and find it very difficult to see deliveries more than a week old and understand how the fee amount has been created, so i end up calling the cooperative to get the information.

USE CASE 3: I am a local last mile provider and I have been asked to delivery 500 pocket calendars to every lawyer in the city as a promotional campaign by the lawyers association. I have uploaded 500 orders to the platform with the cooperatives DIY import excel, and the deliveries will take place over the next month. now I can't find the status of the deliveries, but I have to send a note of delivery to the client every week showing how the service is going, and have to ask the cooperative to make it manually. I also am getting 30 emails a day and don't know how to make this stop. I had hoped to hand off a task I didn't want to the local cooperative and not think much about it, maybe download an excel with the deliveries finished at the end of each week, and it's become a headache.

USE CASE 4: We are a local magazine that has 150 weekly deliveries with the cooperative. Usually things go fine, but sometimes a client calls saying they haven't received their magazine for a week or two. Right now I have no way to easily check how that specific delivery is in the platform, since I would have to press "next page" a few dozen times, and I end up calling the cooperative.

**Comment by AdrienSICKLO** [comment]
I guess it is related to another topic but also very much linked, notifications are currently standardized for all users. 
Having an option depending on user to have or not certain notifications can be good.


What is also missing is a global receipt for all deliveries. People in the food side of the business receive one. For deliveries, one exists but it is hard to find and not great yet. But it already exists which is a good thing. (GIF attached). There's probably some work on this to know what kind of info we would need on this receipt:
![Receipt for deliveries](https://user-images.githubusercontent.com/59842043/227173570-5432888e-f950-46a9-9079-281d275b9b53.gif)

**Comment by ERAMANrepartos** [comment]
![image](https://user-images.githubusercontent.com/77277854/227948214-e6f0beab-95a0-46d2-908b-061fa013fd55.png)

**Comment by y-bele** [comment]
## Panel for stores
I made a rough sketch to approach what Paul was asking for. And I have some questions for you and also maybe @alexsegura about what we can do technically.

## Questions 
**Search by client name:** Do we have the ability to suggest clients?

**Search by address:** suggest address or make an approximation? What address do we want to search?  I assume that it will be the delivery (because for a store always will be the same place where the pick up happens)

**Search by order number:** Seeing that the code of the order doesn't follow a straight line should we suggest something? The orders are like #1 #27 #39... (I don´t know if we can make them like 1,2,3,4...)

**Search by date:** From - To, only from or only to? This will be interesting I think

**Random:**
- Do we need to be able to order the orders?
- Should we know the price? What the customer pays or what the owner have paid to a coop?
- Order by price?

## Sketch

![Panel_stores](https://user-images.githubusercontent.com/36508137/228594802-8797ab1e-fc25-4710-9fd7-db03bd439cd9.png)

**Comment by AdrienSICKLO** [comment]
Hello @y-bele 

I'll let @alexsegura answer on the "possibilities".

I think that the price is clearly something missing here. We should definitely make it visible for our client with some kind of "total for the month" aspect to it
and also give them the possibility to export this data.

**Comment by alexsegura** [comment]
Ok I'm noticing that the search bar only appears for administrators. 

A quick win would be to add the search bar for store owners. It is already [splitted by store](https://github.com/coopcycle/coopcycle-web/blob/24841ed2d48e70ddf896ad14bca0b11e23e97a3a/src/MessageHandler/IndexDeliveriesHandler.php#L67), so that stores can only search their own deliveries.

**Comment by ERAMANrepartos** [comment]
@alexsegura there isn´t currently a github issue about the search function you have described above right?

**Comment by ERAMANrepartos** [comment]
@alexsegura ?

**Comment by Paul-Eraman-CoopCycle** [comment]
Various things finished, what's left is in 3506, closing
