### ISSUE TITLE
As a dispatcher in the Admin Dashboard the filter for time range only affects assigned tasks, not unassigned tasks

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3628]
**Describe the bug**
When I use the time range filter in the admin dashboard it only works on unassigned tasks (and even then imperfectly, sometimes for certain tasks it does filter 😕 )

**To Reproduce**
1. Have tasks distributed throughout the day, some assigned some unassigned
2. Use the filter to not see some unassigned tasks
3. See that they remain visible both int he top right in the list, and also in the map

**Expected behavior**
They disappear from the map

**Screenshots**

![filternotworking](https://github.com/coopcycle/coopcycle-web/assets/77277854/e2f3bbc2-2f03-4e6e-9366-0ba12ae7949d)

**Desktop (please complete the following information):**
 - Firefox browser

**Comment by lucasferraro** [comment]
After some research I figured out that there's a filter ("Always show unassigned") that is "in conflict" with this issue.
"Always show unassigned" enabled means that all unassigned tasks will be shown no matter which filters are selected (time range, tags, etc).

But if "Always show unassigned" filter is disabled the filters like time range and tags works fine for unassigned tasks.

Check this test:

https://github.com/coopcycle/coopcycle-web/assets/4819244/6c948c32-1868-467e-9c60-75134743bd63

@Paul-Eraman-CoopCycle Do you think that this issue is resolved with this? Does it make sense to have that "Always show unassigned"? 
Maybe an improvement can be: "Always show unassigned" filter to be "disabled" by default so filters work for all tasks at least the user select that unassigned should not be filtered for some reason.

**Comment by lucasferraro** [comment]
Ok I'll move forward with 2 and 3 suggestions. 
The first suggestion I don't really understand what it means. Does it mean to have a new tab like 'Unassigned' and in that tab the filter? Or it means to move the filter inside the 'Time range' tab? Any way, I don't agree for both cases, I think is better to keep the filter where is now, in a 'General' section because is a general filter that impact in all the others if it's enabled.

**Comment by Paul-Eraman-CoopCycle** [comment]
🥳
