### ISSUE TITLE
Issue with accounting for all manual prices in final excel

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3771]
**Describe the bug**
[A clear and concise description of what the bug is.
]
(https://coopcycle.slack.com/archives/C4UT4DGQ3/p1694791286410409)

If someone makes an order, then adds a manual price after it is completed, this does not appear in the final export excel

**Comment by alexsegura** [comment]
It is because when exporting orders, we only export orders with `state = fulfilled`. 

When creating a delivery with an arbitrary price, the order is created with `state = accepted`

https://github.com/coopcycle/coopcycle-web/blob/805d37bfd405f8c40dd5578b6b009ba841148a9a/src/Controller/Utils/DeliveryTrait.php#L136

This is the expected behavior. Admins need to manually fulfill the order.

**Comment by 0bi0ne1312** [comment]
The problem is that when I discovered this part of the CoopCycle website and its requirements (the "commande" panel) I spent a not so small amount of time terminating all the  accepted tasks from august (as I was planning to do the accounting for this month in particular).
But even after terminating it, it didn't export... is there a timing for the database to update so the exportation is effective for all these new terminated tasks ?

Now, I added this task to my daily routine to make sure that every commande is terminated. I Hope so it will work better for me at the end of next month 🫣

**Comment by Paul-Eraman-CoopCycle** [comment]
So something strange is happening i think. Create orders is activated [photo1] but in their deliveries/orders history page there are no order codes [photo2]. However, in the excel export from the orders page, there are order codes [photo3]. In the admin panel, the tasks also do not have order codes in their description [photo4].
Could this have to do with being orders that come from the API? I´m assuming these are other consequences of the same underlying issue, am I wrong?

![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/5cb8050a-1d64-4f10-a688-6a4566eab4b0)



![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/86fd1c7c-dcde-4e2b-b290-dc7317307595)



![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/b1356204-8a9a-422b-bf98-bab90b9b4ad9)



![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/859026e7-7c53-4067-9778-1f62c745f863)

**Comment by 0bi0ne1312** [comment]
It is probably the good example as from now on orders are created for Carrefour shops... But it sill reflect the type of problem we had, and still have if the order is not made before the delivery.

**Comment by Paul-Eraman-CoopCycle** [comment]
It was fixed but we forgot to close until now 🤦
