### ISSUE TITLE
Introduce business accounts

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3782]
We need to introduce a new `BusinessAccount` entity, to hold the "platform catering" feature. 

A `BusinessAccount`: 
- Has a name
- Has an address
- Has a list of restaurants
- Has a list of customers

The new `BusinessAccount` concept shares concepts with the `Hub` concept, but should be implemented as a separate feature. 

Administrators should be able to: 
- Create a new business account
- Configure the list of restaurants
- Input the email of the account manager, that will manage the business account

We will also need a new `BUSINESS_ACCOUNT` role, to check permissions of the account manager. 

We need to have the `BusinessAccount` feature behind a feature flag, so only instances with it enabled can see it.

**Comment by lucasferraro** [comment]
This is how it looks the work in progress of this feature:


https://github.com/coopcycle/coopcycle-web/assets/4819244/151c7490-9f43-4cc2-9dc9-f25610068bb9

Observations:
- There's a new feature flag in `.env` file called `BUSINESS_ACCOUNT_ENABLED` which allows to use this feature.
- Administrators can create a business account and send an invitation to the manager to join Coopcycle.
- After send the invitation Admin can't edit the manager email.
- Manager will create a password and register in the platform. (the user will have the new role `ROLE_BUSINESS_ACCOUNT`)
- New `Business Account` section will be available under `My Account` menu.
- Manager will be able to change name, address and only remove restaurants (because today only exists one endpoint to search restaurants and it's available only for `ROLE_ADMIN`)
- TODO: manager should be able to create an invitation link to send to the employees.

Branch of the feature https://github.com/coopcycle/coopcycle-web/tree/introduce-business-accounts
