### ISSUE TITLE
As a customer, I need the possibility to credit more money on my account on top of having the possibility to give back reusable packages

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#3804]
When using reusable packages system, when ordering and IF I already have ordered before, I am only given the possibility to give back my packages, not credit my account.

Whereas maybe I lost them, broke them, or would need to credit anyways. So I would need a "credit my account" button

![image](https://github.com/coopcycle/coopcycle-web/assets/59842043/01e97890-75cb-45d9-8609-29a4365070c0)

**Comment by impec-dev** [comment]
More descriptive expected behavior : 

**1. In the restaurant cart, standardize the message :** 

"Votre commande présente X plats adaptés à la livraison zéro-déchet, pour un total de Y,00 € de consigne
Vous avez Z,00 € sur votre cagnotte Green
Vous avez W boîte chez vous, pour un total de V,00 €"

then 1 sentence depending on the situation: 
"=> C'est tout bon, vous pouvez finaliser votre commande !
**=> OR Il vous manque X€ de consigne pour finaliser votre commande zéro-déchet**"
when applicable : 
"Nous vous suggérons de rendre vos boîtes lors de la livraison"

then 1 unique button "manage my deposit"/"gérer ma consigne"

2. When you click on manage my deposit button, one unique screen in all cases - as per screen attached
=> information on the process
=> a part to return the reusable packagin you have at home if possible
=> a button to add money on the account
=> a recap

![gérer la consigne](https://github.com/coopcycle/coopcycle-web/assets/83373118/4f6346cb-7ea5-4c9e-9048-bebf32060b8f)

**Comment by impec-dev** [comment]
Video of the encountered problem : 

![plus de consigne que de boites](https://github.com/coopcycle/coopcycle-web/assets/83373118/88221c4a-908a-4a54-a571-bb9b5e1bc6e2)
