### ISSUE TITLE
When ordering multiple of the same product, the additions (options) don't appear for the restaurant

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#3933]
**Describe the bug**
When making an order with multiple of the same product, it **appears** that this means the ticket as seen by dispatch and by the restaurant does not show additional options that were requested

**To Reproduce**
1. make an order with 5 of some product, choosing an additional option for them (in this case, all 5 had the same option)
2. finish order
3. see ticket in platform for restaurant and dispatch

**Expected behavior**
the additional options should appear

**Additional context**

Order eraman 5F6H

how it is seen when making the order
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/0a90e161-e2b2-4cc6-9b95-f8a58ad0833e)
As it is seen in the restaurant ticket and the admin ticket
![telegram-cloud-photo-size-4-6050892859277689725-x](https://github.com/coopcycle/coopcycle-web/assets/77277854/0841e942-7f91-4e88-ab4a-a189b6feef97)

**Comment by Paul-Eraman-CoopCycle** [comment]
![image](https://github.com/coopcycle/coopcycle-web/assets/77277854/8e7a23dc-2475-4a68-ab14-14dfaff55839)

**Comment by vladimir-8** [comment]
I also can not reproduce it. I tried creating orders from both the web and app and I see that the options are shown:

| | |
|-|-|
|<img width="665" alt="Screenshot 2024-01-17 at 10 58 04" src="https://github.com/coopcycle/coopcycle-web/assets/70273239/e2434fa7-1d9d-45c4-9ae8-8f71056645e0"> | ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-01-17 at 10 58 29](https://github.com/coopcycle/coopcycle-web/assets/70273239/39cb73e5-76a3-4279-8e29-1fdab1a9df2e) |

It seems that there was an issue with this particular order. I see in the `sylius_order_item` table that the option was added (adjustments_total column), but there is no corresponding adjustment in the `sylius_adjustment` table. 

![Screenshot 2024-01-17 at 11 00 24](https://github.com/coopcycle/coopcycle-web/assets/70273239/b27cadb3-f877-4a0b-b3ca-4ac0491c1a65)

![Screenshot 2024-01-17 at 11 00 38](https://github.com/coopcycle/coopcycle-web/assets/70273239/3e03147d-2023-4ba4-8f4a-48ad4ac46cb5)

This could be due to the same root cause as the other issues we sometimes have with orders not appearing and multiple payments. It’s too late to debug the issue with this order. However, I’m adding more logs to help us understand what’s going wrong when it re-appears: https://github.com/coopcycle/coopcycle-web/pull/3965. So please let me know if you see an order with a similar problem.

**Comment by Paul-Eraman-CoopCycle** [comment]
Havent heard a complaint since, closing until further news
