### ISSUE TITLE
In a courier task list, it is not possible to reorder multiselected tasks (it crash) 

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#3949]
![Peek 04-01-2024 12-55](https://github.com/coopcycle/coopcycle-web/assets/4426585/ac6f97ec-41f3-4e44-9381-1b0a0687095f)

**Comment by alexsegura** [comment]
It is technically fixed in #3954. 

![multi-drag-tl](https://github.com/coopcycle/coopcycle-web/assets/1162230/ae537d42-9ce4-4b31-9788-7865788e6eb0)

As a small improvement, can we have a visual feedback of the number of tasks being dragged? 
Just like when dragging from unassigned to assigned (see the small (2) on the top right).

![multi-drag-tl-group](https://github.com/coopcycle/coopcycle-web/assets/1162230/dd58e109-b7f3-4cad-9e4c-8968da730915)

You may close this issue and reopen a new one for this small improvement.

**Comment by Atala** [comment]
Yes I wanted to do that but I didnt find out why the number of tasks was not showing automatically?  I searched in react-dnd but I didnt find
