### ISSUE TITLE
Make the tour column toggable (and delete previous show/hide tour panel setting)

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#3999]
Make the tour column toggable

![image](https://github.com/coopcycle/coopcycle-web/assets/4426585/12a0a605-b5da-40ed-a88e-c40ad3d1f884)

**Comment by Atala** [comment]
@AdrienSICKLO thinks it should be a global setting for the whole instance/coop. Which makes sense, in regards tht if your coop is using tours, then you want every dispatcher to have the same display

what do you think @Paul-Eraman-CoopCycle ?

**Comment by Paul-Eraman-CoopCycle** [comment]
If it can be personalized per user thats better, but i dont know how much more work that is

**Comment by AdrienSICKLO** [comment]
How do you see that working @Paul-Eraman-CoopCycle ? 
Cuz for example, we were doing some tests with Aloïs, and he made a tour, and when I logged in on my end, there was no route pannel, so like 5 tasks had disappeared from the dispatch. When I activated the pannel, they reappaered. 
So in my opinion, I don't see how it could work differently for users of the same platform because the only other solution I see is displaying the tasks without the tour, but kinda creates a franckentein, right?

**Comment by Atala** [comment]
- same work to do per user or per coop I would say
- agree with adrien, it is an issue if in a coop some pple see tours other see not the column, because they cant see tasks that are in the middle column. i do think it should be at the coop/instance level. (if there is a setting, the less work is to show to everybody)

**Comment by Paul-Eraman-CoopCycle** [comment]
Yeah that makes sense, hadn't thought of that
Ok let's go with global then

**Comment by Paul-Eraman-CoopCycle** [comment]
I think we should actually do this: make it collapsable, and it shows if there are tasks in that section if its closed. then no toggling at all. in fact, shouldnt all the columns be toggleable?



![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/90459fbe-95dd-4077-abee-0f518cd0f400)

**Comment by Atala** [comment]
sounds like a good idea. 

the design should also work for columns dispaly of assigned/tours/unassigned, so a vertical drawer.

if everything is togglable then we will be not far of a mobile design that works
