### ISSUE TITLE
Incident reset after reschedule ?

### ISSUE THREAD

**Issue by r0xsh** [coopcycle/coopcycle-web#4005]
1. why should we override the previous "incident statute" if the task was rescheduled? task had an incident and it should be kept 
2. also, I guess rescheduling should create an incident as well, so we can keep track of it. I think it will nice but not 100% sure what do you think ? what @Paul-Eraman-CoopCycle  do you think about registering reschedule as incident ?

_Originally posted by @Atala in https://github.com/coopcycle/coopcycle-web/pull/3952#discussion_r1487665677_

**Comment by Paul-Eraman-CoopCycle** [comment]
1. I agree that the "flag" or whatever that shows that there is an incident should remain. i guess maybe i dont totally understand which thing (status vs flag) should be which, i think i agree with what you are saying. it should now be unassigned because reschedule, (not automatically assigned to the same messenger) but should be an "incidented" task that appears in the incident resolution page we talked about and so on
2. rescheduling should be an incident yes. i suppose we could make it a pop up that asks if it should count as an incident (i can think of times it wouldnt need to be) but for now lets keep it simple and keep on the side of caution (better more incidents and we reduce later than not registering things)

**Comment by Paul-Eraman-CoopCycle** [comment]
this is the current behavior, so all good! question resolved. when reschuling, it will be unassigned by default
