### ISSUE TITLE
Tasks have strange order when put into a route

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4066]
When a series of tasks is put into a route they end up with first the dropoffs and later the pickups in a strange and unhelpful order.

To replicate: 
1. select a number of tasks
2. while they are selected, click the plus button to create a route. 
3. name the route
4. see the strange order

What is expected to happen:
They are ordered in the same order that they were above in the unassigned list, especially with the dropoffs first and pickups second

Video:
![routeproblemas](https://github.com/coopcycle/coopcycle-web/assets/77277854/01c60363-6f64-4067-b49b-8964e987ec96)

**Comment by Atala** [comment]
actually the default order for unassignedtasks is sorted by date of completion. i will put this as the default order as well for newly created tours

**Comment by Atala** [comment]
we need to dig with real world use cases because with my test data it is difficult for me to see what is useful

for example if we dragNdrop one pickup it picks the dropoff with it and I think it will place the dropoff just after the pickup **even if** in the task selection we have stuff to be done before

I am not exaclty sure on what happenned on your gif

we will check together

**Comment by Paul-Eraman-CoopCycle** [comment]
what was expressed to me by mensakas was that if it could be in the order that it is in unassigned, that would make sense 

but i dont know honestly

we should do a real workshop about routes with multiple people soon

**Comment by Atala** [comment]
OK seems good for now, I can do that

so when you create tours + when you DND to a tour from unassigned ?

**Comment by Paul-Eraman-CoopCycle** [comment]
yep, thats what has been communicated to me
