### ISSUE TITLE
When I try to add a product to the cart, I see a progress indicator for a few seconds and then the cart appear empty as if the product was not added (in reality it's added, but not displayed) It happens only for one specific product

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-web#4090]
**Describe the bug**

When I try to add a product to the cart, I see a progress indicator for a few seconds and then the cart appear empty as if the product was not added (in reality it's added, but not displayed) It happens only for one specific product

**To Reproduce**
1. Go to https://sicklo.coopcycle.org/fr/restaurant/47-gustavo
2. Click on 'MENU KEBAB VEGAN'
3. Select all required option and try to add it to the cart
4. See the cart is still empty
5. (try to add another product and 'MENU KEBAB VEGAN' will appear in the cart)

**Expected behavior**

The product should be added to the cart immediately

**Additional context**

I found `504 Gateway Timeout` logs for this request, and also for some others:

https://app.datadoghq.com/logs?query=%40http.status_code%3A504%20&cols=host%2Cservice&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1710969294876&to_ts=1711228494876&live=true

Maybe we can try some of these suggestions:

https://stackoverflow.com/questions/24453388/nginx-reverse-proxy-causing-504-gateway-timeout

**Comment by vladimir-8** [comment]
Timeline of what's happening on the `POST /fr/restaurant/47/cart/product/c67df26b-dbda-489d-ae0d-a7f788b79cc9` request

```
[
  "web01", {
    "message": "Matched route \"restaurant_add_product_to_cart\".", "POST /fr/restaurant/47/cart/product/c67df26b-dbda-489d-ae0d-a7f788b79cc9",
    "channel": "request",
    "datetime": "2024-04-12T17:13:34.598832+02:00"
  },

  "datadog", "nginx", "status_code": 504, "12/Apr/2024:17:14:34 +0200",

  "web01", {
    "message": "Order #310252 | OrderLogFinishProcessor | processing finished",
    "channel": "checkout",
    "datetime": "2024-04-12T17:15:27.295267+02:00"
  }
]
```

**Comment by alexsegura** [comment]
It is because this particular product has a lot of variants (more than 9000). 

When the customer adds a product to the cart, we try to match an existing variant. 
This is done in `LazyProductVariantResolver::getVariantForOptionValues`. 

The current implementation does a stupid loop over _all_ the variants, trying to match one. 

https://github.com/coopcycle/coopcycle-web/blob/25915ae25f57937cf75b036910969dd5908632e8/src/Sylius/Product/LazyProductVariantResolver.php#L54-L67

It is doing lots of SQL queries to load the variant options, but that's quite fast, what's slow is that there are lots of objects, it fills up the PHP memory. 

A better implementation would be to try to match an existing variant in database directly in one call (seems quite hard). 
At least, not iterate over all the objects, and try not to fill up the memory.
