### ISSUE TITLE
When i make a business account user invitation WITHOUT an associated restaurant group i create a 500 error

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4155]
I go to https://demo.coopcycle.org/admin/restaurants/business-accounts and press make a new business account. I fill in the name and email for a new user but NOT the restaurant group associated and click send. When I then go to my email, click the registration link and open the page to fill out my user information, clicking next makes a 500 error. 

![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/e74809dd-20a8-4fb4-a404-c200fb78042d)
![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/5355cfd4-4b20-4818-a61d-46ce9ad73a4a)

**Comment by lucasferraro** [comment]
I'm checking this issue in my local environment.
I think the issue is not related to the existence or not of a restaurant group associated with the business account.

In my case I'm able to reproduce the issue if I open the invitation link in a browser where I have (or I recently had) an opened session as an admin user. Maybe you can check if it happens to you in the same case. 
BTW, there's a bug that needs to be fixed, but as a workaround, if you are blocked just check to open the link in a browser where you are not logged in.
