### ISSUE TITLE
text is wrong for a business account link

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4220]
When activating a business account as a business account admin after the "here is your link to share the account" page i get this:

<img width="921" alt="Screenshot 2024-04-26 at 23 04 00" src="https://github.com/coopcycle/coopcycle-web/assets/77277854/24aa721c-6e50-47e0-9f2a-9c8cba87b3d7">

the button should say something like "take me to my account" not "complete my order" since there is no order being made

**Comment by lucasferraro** [comment]
I think this has been fixed in this issue https://github.com/coopcycle/coopcycle-web/issues/4311 where we changed the "congratulations" section adding a button which redirects to the Business Account settings page.
You can see a GIF of that implementation in the PR: https://github.com/coopcycle/coopcycle-web/pull/4340#issuecomment-2139657874

**Comment by Paul-Eraman-CoopCycle** [comment]
yep, its repeated
