### ISSUE TITLE
when activating a business account, when i click "create order" it takes me to an order page which i dont need

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4221]
when clicking "take me to my order" the link takes me to
<img width="921" alt="Screenshot 2024-04-26 at 23 06 40" src="https://github.com/coopcycle/coopcycle-web/assets/77277854/da614caa-2281-4da9-8ec4-5c848dea3b21">

it should take me to my business account page
<img width="921" alt="Screenshot 2024-04-26 at 23 07 45" src="https://github.com/coopcycle/coopcycle-web/assets/77277854/8de36053-7b07-4a45-af9c-41f040f69f18">

by clicking this link i also get taken to this same page, which makes a recursive loop
<img width="921" alt="Screenshot 2024-04-26 at 23 07 57" src="https://github.com/coopcycle/coopcycle-web/assets/77277854/f36416fe-d31b-4e8b-a417-498c3b714864">

<img width="921" alt="Screenshot 2024-04-26 at 23 08 40" src="https://github.com/coopcycle/coopcycle-web/assets/77277854/66053108-c9ae-487d-97b3-3f680531fe34">

**Comment by vladimir-8** [comment]
@Paul-Eraman-CoopCycle not sure I understand what you mean by click on "create order" / "take me to my order". On which page do you see them?

When I activate an account I see this page, which looks a bit broken, but due to other reasons:

1. `Personal account creation` label
2. Image is not aligned / redundant?

![Screenshot 2024-04-30 at 14 50 39](https://github.com/coopcycle/coopcycle-web/assets/70273239/3119a68c-74b6-499f-97d5-5d234f932253)

**Comment by lucasferraro** [comment]
@Paul-Eraman-CoopCycle I don't understand the issue here. You are mentioning links that I can't find in the platform:

`when i click "create order" it takes me to an order page which i dont need`
I can't found any place where after activating a business account we are displaying a link "create order".

`when clicking "take me to my order" the link takes me to...`
Where are you clicking "take me to my order"? I can't find that link

I'm trying to reproduce this in my local environment and this is what I have:

**Activating a Business Account with an existing email**


https://github.com/coopcycle/coopcycle-web/assets/4819244/cb1399bd-2a26-4766-87cb-76101ac7795b

**Activating a Business Account with a new user**


https://github.com/coopcycle/coopcycle-web/assets/4819244/01b8a9e9-65d7-48d0-89de-b78310b65473

**Comment by lucasferraro** [comment]
@Paul-Eraman-CoopCycle please check comments above, this needs more info/clarifications. Thanks

**Comment by Paul-Eraman-CoopCycle** [comment]
i think this was from a while ago and changes we have made since then solved this, closing
