### ISSUE TITLE
The invitation link is shown before end of registration process, so if you don't notice you think your never finish your registration

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4311]
The invitation link to share should be shown after you have completed registration. Otherwise you may never finish.

**Comment by lucasferraro** [comment]
@Atala 
Since the last step of the registration (business account manager) is just the screen where we show the link and the button to finish the process, should we keep that screen or just end the flow in the 2nd step?
**This is the screen.**
<img width="600" src="https://github.com/coopcycle/coopcycle-web/assets/4819244/09cef238-66f5-45fa-a9b1-0f7bfcbded25" />

**Where do you think that should be better to show the invitation link? In the screen where we show the success message?**
<img width="600" src="https://github.com/coopcycle/coopcycle-web/assets/4819244/26fa1878-cc97-4e75-9972-7c9b8e9e21e4" />

Or maybe, the link of the success message instead of redirect business account managers to this screen (personal setting info)
<img width="400" src="https://github.com/coopcycle/coopcycle-web/assets/4819244/1fd7db9c-a1ed-4a71-8ef2-219ee42ff0cf" />
Change it to redirect them to the buiness account settings page where the invitation link is displayed?
<img width="400" src="https://github.com/coopcycle/coopcycle-web/assets/4819244/6383c999-eb3d-410e-93c7-1359d8f6bd1a" />

**Comment by Paul-Eraman-CoopCycle** [comment]
I would put it both in the "congratulations" page with an explanation "uset his link below to invite workmates to..." 
and then maintain that button "check it out" which should take you to the business account settings where the link is also displayed

**Comment by Atala** [comment]
+1

what we want is really that first the admin finishes the signup THEN see the registration link

so either : 
 - solution 1 : move the link on the registration page
 - solution 2 : create the admin account + login and so on on the 2nd step "company  registration" completion

whatever is easiest for you.
