### ISSUE TITLE
On the platform, when a restaurant accepts a command it happens sometimes that the order doesn't go from "new" to "accepted" column without a refresh

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4370]
- Reported by Naofood
- In this case the dispatch person has to call the restaurant to know what is going on about the order, and the restaurant tells the dispatch "but i accepted it on the tablet"

![image](https://github.com/user-attachments/assets/de2de4b9-16eb-416a-916d-259d70df6149)

**Comment by vladimir-8** [comment]
To investigate further, I need a few cases where this issue happened, ideally with the following info:

- date and time
- link to the web page or screen name in the app (if possible, a screenshot or a video)
- description of the expected behaviour
- description of what actually happened (if it's not self-evident)

**Comment by Paul-Eraman-CoopCycle** [comment]
We will get more info in Nantes next week

So far it seems it is affecting Rennes and Naofood, but not Eraman
Is apparently a constant/regular occurrence

New orders do not show up in  /admin/foodtech/dashboard/DATE even though they have been created
