### ISSUE TITLE
Geotracking issues to investigate

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#439]
Most users (Berlin, Madrid, Nantes, Bruxelles) report couriers not seen in the dashboard. Here's an issue to discuss about investigations.

**Comment by couleurmate** [comment]
What are events' behaviors to be expected ?

**Comment by alexsegura** [comment]
I think it's a issue with the app's permissions...

**Comment by AmelieA** [comment]
When you go back from the map, the gps location is no longer shared with the website. But i wouldn't call that a bug. Do the courier experiencing the problème see the little coopcyle icon on top ? The one telling you about your gps data sharing ?

**Comment by Atala** [comment]
I think the expected behavior should be :
 * as long as the app is running (even in the background or outside the map screen) and location-sharing enabled the courier on the map is updated correctly
 * the courier greys out and then disappear after a while when the position is not received correctly

**Comment by alexsegura** [comment]
I think the problem of update on the dashboard pointed by @PasLoin can be due to this error that happens regularly: 

<img width="540" alt="capture d ecran 2018-09-27 a 09 56 23" src="https://user-images.githubusercontent.com/1162230/46131367-be844a80-c23b-11e8-93b3-11fa714eb601.png">

It is a problem with Socket.io, we need to make it disappear.

**Comment by alexsegura** [comment]
I have downgraded `socket.io` to `2.0.3` to see if it fixes the problem.

See #464

**Comment by gosaric** [comment]
Downgrading does not solve the problem.

**Comment by alexsegura** [comment]
I think it's working well now, work continues in #527
