### ISSUE TITLE
incident list set wrong

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4504]
![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/9d307d24-c5cc-4339-918d-b0c6f1b558b1)

this is a task related to Carrefour Feydeau, which has a custom incident list associated with it, but it is still pulling the DB Schenker list

**Comment by Paul-Eraman-CoopCycle** [comment]
Yes, exactly

**Comment by r0xsh** [comment]
I've finally pinpointed the issue—it was a UI/UX problem. The form wasn't validating because the SIRET number was incorrectly formatted. Since the data was invalid, nothing was being saved, and that's why the custom failure reason wasn't working.

I've resolved this on your instance for Feydeau, @AdrienSICKLO
