### ISSUE TITLE
Export more user data from user list

### ISSUE THREAD

**Issue by chatteaunez** [coopcycle/coopcycle-web#4626]
In order to analyse user data, and efficiently create mailing lists.

I want to be able to export the data from all available fields in the user list.

Whereas currenly the only columns in the csv file are the users' name and e-mail address.

We would like to be able to get the total number of order, date of last order, date of inscription.

**Comment by Paul-Eraman-CoopCycle** [comment]
we are going to improve the ability to search, filter, and see info in the user database, but I understand that downloading the csv is a problem for data protection laws, since we have to show that we are not passing user data on to other third party entities. Track this generally with the tag "customer service"

closing as not planned
