### ISSUE TITLE
Auto-complete pending pickups when finishing associated dropoffs

### ISSUE THREAD

**Issue by r0xsh** [coopcycle/coopcycle-web#4774]
## Problem
Riders receive a blocking error `You have to finish task #{pickup_task_id} before completing this task` when trying to complete dropoffs. This is frustrating since the pickup was likely already physically completed.

## Solution
When completing a dropoff with pending pickup:
- Prompt user to auto-complete the associated pickup task
- If confirmed, complete both tasks
- If declined, show current error

## Acceptance Criteria
- [ ] Add confirmation prompt for auto-completing pickup
- [ ] Implement force-completion flow
- [ ] Log forced completions
- [ ] Update error message to be more actionable

**Comment by alexsegura** [comment]
Yes a possible implementation to autocomplete would be first, to accept an optional `autocomplete=true` parameter in the payload, and then instead of checking if previous task is completed, it would iterate over the current task + all the previous tasks, and complete them. 

https://github.com/coopcycle/coopcycle-web/blob/798a071464e2a6435b717f13eac5a49ec2b7d0bb/src/Domain/Task/Handler/MarkAsDoneHandler.php#L39-L46
