### ISSUE TITLE
Allow users to show interest in unlisted restaurants

### ISSUE THREAD

**Issue by ofelt** [coopcycle/coopcycle-web#491]
# Feature context
Despite all the good values from CoopCycle it can be hard for restaurants to make the switch (or just use it in addition to others providers).  
They can be skeptical, cautious or just waiting to see the development of the service in their town. Yet this is critical for cooperative to be able to generate sufficient revenues and survive, as the more restaurants they get the more work they get.
One way to encourage them is to show them that clients are already waiting for their restaurant to order food. A bit similar in the idea to what Liberapay [is doing](https://en.liberapay.com/explore/pledges)

## User Stories :
- Oliver, a client, is looking for it's favorite vegan restaurant in Lyon. He use the search box and type his home address but the restaurant doesn't seem to use this service yet he would like to let them know that he would be willing to order from them
- Camille, an associate of the cooperative, is looking to prospect for new restaurants for her users but doesn't know which one she should go first. She goes to the admin panel and look under the new section "Pledges" and sees a list of restaurants her users are interested in
- Camille, is prospecting a new restaurant that she previously spotted. The owner seems interested but hesitant because of the ratio hassle/gain. She tells him about the benefits and growth of her cooperative and to support her claim she shows him that already 20 clients are interested in his restaurant (optional: with an average of 200€ revenue per week)

## UI Stories
- At the bottom of the restaurants page and the search results page, add a link "Looking for a restaurant that is not listed ? Click here to let them know you are interested".
- From the previous link show a form with two sections, one for the restaurant and one for the pledge and a submit button "I'm interested". Restaurant section : Show a list of already submitted pledged restaurants to select from and a link "Not in this list ? Click here to add it" that make a form for the restaurant appear with two fields (name and address).
(optional) Pledge section : Show a form with the average amount of the client's cart and the frequency of his orders
- In the admin panel add a link to a new section called "Pledges", there show a list of the restaurants pledged by users orderable by the number of interested users (optional, by average revenue per week)

**Comment by AmelieA** [comment]
I really like it ! 
Not a priority for us (as keeping our restaurant by offering a bug free version of the app is still our main préoccupation) but it would help in the futur !

**Comment by alexsegura** [comment]
Let's do this! 🚀 

Here are some technical details for you @arnomasson 

### Database

[Symfony docs for Doctrine](https://symfony.com/doc/current/doctrine.html)

Create a new entity called `RestaurantPledge` in `src/AppBundle/Entity`. 
Don't forget to create the **migration** file. 

The `RestaurantPledge` entity should have the following fields: 
- name (the name of the restaurant)
- address (the address of the restaurant)
- user (the user that created the pledge)
- state (the state of the pledge. Can be `new`, `accepted`, `rejected`)
- createdAt (the date when the pledge was created)

⚠️ 
We are using the YAML mapping, not annotations as described in Symfony docs, so you will need to create the Doctrine mapping in `src/AppBundle/Resources/config/doctrine`

### Frontend

1/ Add a button/link at the end of the restaurant list and/or in the footer, saying "Suggest a restaurant", or something like this, that leads to a new page.

2/ Create a new action method/route in `RestaurantController`, called (for example) `suggestRestaurantAction`, with URL `/restaurants/suggest`.

3/ Create a new form type in `src/AppBundle/Form` named `RestaurantPledgeType`, that creates a new `RestaurantPledge`. You will of course need to make sure the name & address are not empty, etc... 

4/ Once the form is submitted and valid, save the new `RestaurantPledge` in database, redirect to a confirmation page showing a message "Thank you for suggesting a restaurant!", and send an email to administrators saying a new pledge has been submitted.

### Backend

Pledges need to be moderated first, because we can't let people suggest restaurants with offending names. So, when a new pledge has been created, administrators need to moderate them

1/ Create a new method/route in `AdminController` named (for example) `restaurantPledgesListAction`, showing a list of pledges, as a simple HTML table, with the following columns: name, address, user, state. 

2/ On each row, when the pledge is in state `new`, there are 2 buttons "Accept"/"Reject".

3/ To accept/reject the pledge, you will need to create a new form type in `src/AppBundle/Form`, named for example `ModerateRestaurantPledgeType`, with 2 buttons.

4/ When the admin **accepts** the pledge, an email is sent to the user that submitted the pledge, saying "Thank you, your pledge has been accepted, click here blah blah"

⚠️
Only authenticated users are allowed to suggest restaurants. 
So you will need to put the suggest route behind a firewall (in `app/config/security.yml`)

[docs for Symfony security](https://symfony.com/doc/current/security.html)

That's all for now 🙂 
After that, we will need to think about the stuff of "upvoting" suggested/pledged restaurants, but let's do that first.

**Comment by alexsegura** [comment]
@ofelt thank you for... suggesting this 😄
The first version of this feature has been deployed on demo instance 🚀 

https://demo.coopcycle.org/en/restaurants/suggest

Thank you @arnomasson for the hard work 👍

**Comment by ofelt** [comment]
Awesome, thank you for implementing it :) Keep up the good work !
