### ISSUE TITLE
Add a Makefile to complete the install steps

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#69]

**Comment by 4x10m** [comment]
Why a Makefile ?
It add a dependency on Make that is not natively available a some systems but nothing more than shell.
I think we could "just" use as many types of shell scripts as kernels we want to support.

I think to in order to do that, we have to bundle the small part of tasks that we are doing natively in docker. I mean, for example, use docker to download OSM data instead of using wget. Same for Openssl.

This could lead to code differences between scripts, i mean more to needed (not platform dependant) but i think that we can refactor some `docker-compose.yml` parts to encapsulate some behaviors in Dockerfiles.
