### ISSUE TITLE
Improve invoices

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#785]
I think it would be very useful (to customers & to the coops) to improve invoices

On top of my head what I would think of :
 - show VAT number of the coop / the restaurant (montrer les numéros de TVA coop/restaurant)
 - show VAT/tax breakdown (montrer la ventilation, les différents taux de TVA)
 - add the coop and/or coopcycle logo (+ improve UI, for example a table design would be clearer) (améliorer le rendu, mettre le logo de la coop et/ou coopcycle)

Please add suggestions below !

**Comment by cccchurri** [comment]
it would be great to invoice direct over the jobs added to the Coop Platform I'd say. Also by the end of the month or so. Would save a lot of work

**Comment by alexsegura** [comment]
To be completely compliant with the law, I think invoices should be generated as plain files (now, they are generated dynamically).

I mean, once generated, invoices shouldn't be modifiable. 
If the invoice is wrong, you must generate a new invoice.

**Comment by alexsegura** [comment]
We could grab some ideas from [Sylius/InvoicingPlugin](https://github.com/Sylius/InvoicingPlugin).

Unfortunately, we can't use it directly, because it needs full-blown Sylius, and relies on wkhtmltopdf (we are using Puppeteer)

**Comment by alexsegura** [comment]
It is possible to add a custom logo since 3704536fd4a252e0734b208aee7f82458e50e9db

**Comment by alexsegura** [comment]
The custom logo (or a fallback) is displayed as a header since 3e1b59797f6d056386e216413ef5a7abfbedb866

Also, we now use [BafS/Gutenberg](https://github.com/BafS/Gutenberg) to have a clean rendering

<img width="597" alt="Capture d’écran 2019-11-06 à 16 11 53" src="https://user-images.githubusercontent.com/1162230/68310610-99097780-00b0-11ea-88b5-8529bb75505a.png">

**Comment by PasLoin** [comment]
We need also a custom numbering system (seting up first number and some letter to specify specific accounting journal in our existing system). 

Alow also to setting this as a "PRO FORMA" invoice.

**Comment by alexsegura** [comment]
Invoices have been superseded by **receipts** in d26f1f94c18834a619ef3465f90f877518e1c218. 
They should contain all the necessary information to be usable in expense reports (VAT rates, etc...)

Also, since ea0137e132a7703687193decf22010f72a0f72c4, iso codes (SIRET, RCS, TVA) are mandatory in France.

<img width="569" alt="Capture d’écran 2019-12-04 à 16 33 55" src="https://user-images.githubusercontent.com/1162230/70156449-3e196f00-16b4-11ea-9dc7-304596fa0482.png">

**Comment by CCCC-Jorrit** [comment]
This is mainly for restaurants at the moment or also for other deliveries?

**Comment by alexsegura** [comment]
@CCCC-Jorrit it's only for food orders.

**Comment by Atala** [comment]
Should we open a new issue for :
 - invoice for restaurant owners
 - invoice for stores
?
