### ISSUE TITLE
Bug when I import tasks on saturday

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#905]
I use csv files for reccurent tasks (one csv for each day of the week). I uptdated some informations in all csv files and I imported the csv files for the next week. When I try to import the csv files of the 2 next saturdays, the displaying of the task on the dispatch's screen is the old csv file. @alexsegura  if you want my csv files, I can send you in a private message on slack

**Comment by alexsegura** [comment]
It is because some tasks you imported have the **same** value for before & after. 
Since 69905390cc9dde4c84e315eaca392af975e70e91, the tasks are retrieved from database using range operations (it's more accurate). As a result, the time range is equal to zero, and the tasks are ignored. 

The import will now trigger an error in this case.

**Comment by PasLoin** [comment]
We use more and more import csv from our customer and they put same value for before and after because of precise time range needed. Error is displayed but this need changing imput sheet from client. https://coopcycle.slack.com/archives/C4UT4DGQ3/p1574764021032500?thread_ts=1574685023.026300&cid=C4UT4DGQ3
