### ISSUE TITLE
Add the install process for windows

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#92]
`make` doesn't exist !

**Comment by 4x10m** [comment]
Hey yeah.

I'm trying to devellop on windows so i'm going to write here what i have to do to make it working. I'm not trying to make it windows or powershell compliant, i think a cmake have to be created later. What i want here is just to make it running on windows the fatest as i can.

I start from master f5b02c8.

(Sorry for french :p)

By trying to run the makefile, we have:

> PS F:\GitHub\coopcycle\coopcycle-web> make install
make : Le terme «make» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable.

So we have to install make, but let's make it for other dependencies like openssl and wget.

Make is here: http://gnuwin32.sourceforge.net/packages/make.htm
Openssl: https://sourceforge.net/projects/openssl/?source=typ_redirect
Wget: https://eternallybored.org/misc/wget/

we have to download binaries, personnaly i moved them to SSD root folder. We now have to add them to environment variables to be able to call them from powershell.

Go there https://www.computerhope.com/issues/ch000549.htm and apply them same principle to add each binaries folder to Path.

That's not that all because you have to do some modification in the Makefile:
- Making a directory that already exists with "mkdir -p" throw an error causing the script to stop.
We can fix that by doing "@[ -d var/jwt ] || @mkdir -p var/jwt" instead of just "@mkdir -p var/jwt" this will conditionally create directory following its existence.

- "$(MAKE)" could cause an error with spaces in make path. Fixed by ""$(MAKE)"" (just double-quote it)

A good ressource on makefiles:
https://gist.github.com/Integralist/9e27ff5582d37ed26aef

WIP

**Comment by 4x10m** [comment]
I think we can improve the process and interroperability of the make file by automating some behavior like cheking if OSM data are present and not re-downloading them.

We can also add argument to provide, for example, postgresql port

Others subroutines could be added like clear to remove all docker containers and image.

But i have a question before thinking to such solutions. You do we use a Make file ? I mean, why do we not use a bash or powershell script ?

**Comment by alexsegura** [comment]
Fixed in #508
